Introduce name spaces in 'systest' like above and separate installation directories of 'systest' files of gfarm_v2 and gfarm2fs packages. (#699)
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/trunk@8219 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/util/gfruntest/gfruntest.in b/util/gfruntest/gfruntest.in
--- a/util/gfruntest/gfruntest.in
+++ b/util/gfruntest/gfruntest.in
@@ -6,8 +6,6 @@ TESTCASES_DIR="$TEST_PREFIX/testcases"
 PARAMETERS_DIR="$TEST_PREFIX/parameters"
 COMMON_SCRIPTS_DIR="$TEST_PREFIX/common_scripts"
 
-DEBUG=""
-
 #
 # Result codes
 #
@@ -39,28 +37,12 @@ log_error()
 }
 
 #
-# Load script files from common_scripts directory.
+# Output an error message with usage.
 #
-load()
+log_usage_error()
 {
-	if [ $# -lt 1 ]; then
-		return 1;
-	fi
+	echo "$PROGRAM: error: $@" 1>&2
 
-	for FILE in $@; do
-		if [ -f $COMMON_SCRIPTS_DIR/$FILE ]; then
-			. $COMMON_SCRIPTS_DIR/$FILE
-		else
-			log_warn "failed to open script file \"$FILE\""
-		fi
-	done
-}
-
-#
-# Output an usage.
-#
-print_usage()
-{
 	echo "Usage: $PROGRAM [option...] testcase [<argument>...]"	1>&2
 	echo "Option:"							1>&2
 	echo "  -d                  debug mode"				1>&2
@@ -70,6 +52,33 @@ print_usage()
 	echo "  -p <parameter_file> specify the test parameter file"	1>&2
 	echo "  -j <classname>      specify the classname and outputs xml file" \
 		1>&2
+	
+	exit 1
+}
+
+#
+# Load script files from common_scripts directory.
+#
+load()
+{
+	if [ $# -lt 1 ]; then
+		return 1;
+	fi
+
+	for MODULE in $@; do
+		FILE=`echo $MODULE | sed -e 's|::|/|g'`
+		if [ -f $COMMON_SCRIPTS_DIR/$FILE ]; then
+			. $COMMON_SCRIPTS_DIR/$FILE
+		elif [ -f $COMMON_SCRIPTS_DIR/gfarm_v2/$FILE ]; then
+			log_warn "use 'gfarm_v2::$FILE' instead of '$FILE'"
+			. $COMMON_SCRIPTS_DIR/gfarm_v2/$FILE
+		elif [ -f $COMMON_SCRIPTS_DIR/gfarm2fs/$FILE ]; then
+			log_warn "use 'gfarm2fs::$FILE' instead of '$FILE'"
+			. $COMMON_SCRIPTS_DIR/gfarm2fs/$FILE
+		else
+			log_warn "failed to open script file \"$FILE\""
+		fi
+	done
 }
 
 #
@@ -142,20 +151,17 @@ while [ $# -ge 1 ]; do
 		;;
 	-)	break
 		;;
-	-d)	DEBUG="-d"
+	-d)	GFSERVICE="$GFSERVICE -d"
 		shift
 		;;
 	-f)	shift
 		if [ $# -eq 0 ]; then
-			echo "option requires an argument -- 'f'" 1>&2
-			print_usage
-			exit 1
+			log_usage_error "option requires an argument -- 'f'"
 		fi
 		if [ -f $1 ]; then
 			GFSERVICE="$GFSERVICE -f $1"
 		else
-			echo "failed to open configuration file \"$1\"" 1>&2
-			exit 1
+			log_error "failed to open configuration file \"$1\""
 		fi
 		shift
 		;;
@@ -164,30 +170,31 @@ while [ $# -ge 1 ]; do
 		;;
 	-p)	shift
 		if [ $# -eq 0 ]; then
-			echo "option requires an argument -- 'p'" 1>&2
-			print_usage
-			exit 1
+			log_usage_error "option requires an argument -- 'p'"
 		fi
-		if [ -f $PARAMETERS_DIR/$1 ]; then
-			. $PARAMETERS_DIR/$1
+		FILE="`echo $1 | sed -e 's|::|/|g'`"
+		if [ -f $PARAMETERS_DIR/$FILE ]; then
+			. $PARAMETERS_DIR/$FILE
+		elif [ -f $PARAMETERS_DIR/gfarm_v2/$FILE ]; then
+			log_warn "use 'gfarm_v2::$FILE' instead of '$FILE'"
+			. $PARAMETERS_DIR/gfarm_v2/$FILE
+		elif [ -f $PARAMETERS_DIR/gfarm2fs/$FILE ]; then
+			log_warn "use 'gfarm2fs::$FILE' instead of '$FILE'"
+			. $PARAMETERS_DIR/gfarm2fs/$FILE
 		else
-			echo "failed to open parameter file \"$1\"" 1>&2
-			exit 1
+			log_error "failed to open parameter file \"$FILE\""
 		fi
 		shift
 		;;
 	-j)	shift
 		if [ $# -eq 0 ]; then
-			echo "option requires an argument -- 'j'" 1>&2
-			print_usage
-			exit 1
+			log_usage_error "option requires an argument -- 'j'"
 		fi
 		JENKINS_CLASSNAME=$1
 		shift
 		;;
 	-*)	echo "$0: invalid option -- '$1'" 1>&2
 		print_usage
-		exit 1;
 		;;
 	*)	break
 		;;
@@ -195,17 +202,22 @@ while [ $# -ge 1 ]; do
 done
 
 if [ $# -lt 1 ]; then
-	echo "test case is not specified" 1>&2
-	print_usage
-	exit 1
+	log_usage_error "test case is not specified"
 fi
 
-TESTNAME=$1
+TESTNAME="`echo $1 | sed -e 's|^.*::||g'`"
+TESTFILE="`echo $1 | sed -e 's|::|/|g'`"
 shift 1
 TEST_EXEC_ID="test_`hostname`_$$"
 
-if [ -f "$TESTCASES_DIR/$TESTNAME" ]; then
-	. "$TESTCASES_DIR/$TESTNAME"
+if [ -f "$TESTCASES_DIR/$TESTFILE" ]; then
+	. "$TESTCASES_DIR/$TESTFILE"
+elif [ -f "$TESTCASES_DIR/gfarm_v2/$TESTFILE" ]; then
+	log_warn "use 'gfarm_v2::$TESTNAME' instead of '$TESTNAME'"
+	. "$TESTCASES_DIR/gfarm_v2/$TESTFILE"
+elif [ -f "$TESTCASES_DIR/gfarm2fs/$TESTFILE" ]; then
+	log_warn "use 'gfarm2fs::$TESTNAME' instead of '$TESTNAME'"
+	. "$TESTCASES_DIR/gfarm2fs/$TESTFILE"
 else
 	log_error "invalid test case: $TESTNAME"
 fi
