fix following socklen_t problem on IRIX (pointed out by tatebe-san): AC_TRY_LINK() always succeed even if socklen_t is not size_t, due to weak type checking of C language.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@15 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1461,32 +1461,40 @@ else
 fi
 rm -f conftest*
 if test "$ax_cv_have_socklen_t" = no; then
+  if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
   cat > conftest.$ac_ext <<EOF
-#line 1466 "configure"
+#line 1469 "configure"
 #include "confdefs.h"
 
-  #include <sys/types.h>
-  #include <sys/socket.h>
-int main() {
+# include <sys/types.h>
+# include <sys/socket.h>
 
-  int rv, s;
-  struct sockaddr addr;
-  size_t len;
+  main() {
+	struct msghdr h;
 
-  rv = bind(s, &addr, len);
+	/* h.msg_namelen should be socklen_t */
+	h.msg_namelen = -1;
+	if (sizeof(h.msg_namelen) == sizeof(int) && h.msg_namelen < 0)
+		return (0); /* int */
+	else
+		return (1); /* size_t */
+  }
   
-; return 0; }
 EOF
-if { (eval echo configure:1481: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  ax_cv_socklen_t=size_t
+if { (eval echo configure:1487: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  ax_cv_socklen_t=int
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  ax_cv_socklen_t=int
+  rm -fr conftest*
+  ax_cv_socklen_t=size_t
 fi
-rm -f conftest*
+rm -fr conftest*
+fi
+
   cat >> confdefs.h <<EOF
 #define socklen_t $ax_cv_socklen_t
 EOF
