regen
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@2363 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20153,10 +20153,10 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-  pthread_srcs='$(PTHREAD_SRCS)'
-  pthread_objs='$(PTHREAD_OBJS)'
-  pthread_cflags='$(PTHREAD_CFLAGS)'
-  pthread_targets='$(PTHREAD_TARGETS)'
+  pthread_srcs='${PTHREAD_SRCS}'
+  pthread_objs='${PTHREAD_OBJS}'
+  pthread_cflags='${PTHREAD_CFLAGS}'
+  pthread_targets='${PTHREAD_TARGETS}'
   ;;
 *)
   if test x"${with_pthread}" = x"no"; then
@@ -20216,6 +20216,9 @@ fi
 
 
 
+
+# sanity check for OpenSSL is deferred, because ${openssl_includes}
+# and ${openssl_lib} may be overrided by Globus autoconfiguration.
 
 ###
 ### --with-globus=GLOBUS_ROOT --with-globus-flavor=FLAVOR -with-globus-static
@@ -20341,10 +20344,10 @@ echo "$as_me: error: Globus installation is incomplete, aborted." >&2;}
  esac
 
  # for conditional compilation which depends on whether globus is enabled or not
- globus_srcs='$(GLOBUS_SRCS)'
- globus_objs='$(GLOBUS_OBJS)'
- globus_cflags='$(GLOBUS_CFLAGS)'
- globus_targets='$(GLOBUS_TARGETS)'
+ globus_srcs='${GLOBUS_SRCS}'
+ globus_objs='${GLOBUS_OBJS}'
+ globus_cflags='${GLOBUS_CFLAGS}'
+ globus_targets='${GLOBUS_TARGETS}'
 
  openssl_includes='$(globus_includes)'
  case ${globus_static} in
@@ -20407,10 +20410,10 @@ if test "${with_mpi+set}" = set; then
 echo "${ECHO_T}using \"${mpicc}\"" >&6
 
  # for conditional compilation which depends on whether MPI is enabled or not
- mpi_srcs='$(MPI_SRCS)'
- mpi_objs='$(MPI_OBJS)'
- mpi_srcs='$(MPI_CFLAGS)'
- mpi_targets='$(MPI_TARGETS)'
+ mpi_srcs='${MPI_SRCS}'
+ mpi_objs='${MPI_OBJS}'
+ mpi_srcs='${MPI_CFLAGS}'
+ mpi_targets='${MPI_TARGETS}'
 
 else
   echo "$as_me:$LINENO: result: disabled" >&5
@@ -21339,10 +21342,10 @@ if ( getconf LFS64_CFLAGS &&
 	echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
-	largefile64_srcs='$(LARGEFILE64_SRCS)'
-	largefile64_objs='$(LARGEFILE64_OBJS)'
-	largefile64_cflags='$(LARGEFILE64_CFLAGS)'
-	largefile64_targets='$(LARGEFILE64_TARGETS)'
+	largefile64_srcs='${LARGEFILE64_SRCS}'
+	largefile64_objs='${LARGEFILE64_OBJS}'
+	largefile64_cflags='${LARGEFILE64_CFLAGS}'
+	largefile64_targets='${LARGEFILE64_TARGETS}'
 else
 	echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -21561,7 +21564,9 @@ echo "${ECHO_T}using \"${ldap_includes} ${ldap_libs} ${libs}\" for LDAP" >&6
 	# this needs to be checked here due to settings of $CPPFLAGS and $LIBS
 
 
-for ac_func in ldap_memfree ldap_set_option
+
+
+for ac_func in ldap_memfree ldap_set_option ldap_start_tls_s ldap_perror
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -21742,7 +21747,9 @@ echo "${ECHO_T}using \"${ldap_includes} ${ldap_libs} \" for LDAP" >&6
 	# this needs to be checked here due to settings of $CPPFLAGS and $LIBS
 
 
-for ac_func in ldap_memfree ldap_set_option
+
+
+for ac_func in ldap_memfree ldap_set_option ldap_start_tls_s ldap_perror
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -21876,10 +21883,10 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_LDAP 1
 _ACEOF
 
-	ldap_srcs='$(LDAP_SRCS)'
-	ldap_objs='$(LDAP_OBJS)'
-	ldap_cflags='$(LDAP_CFLAGS)'
-	ldap_targets='$(LDAP_TARGETS)'
+	ldap_srcs='${LDAP_SRCS}'
+	ldap_objs='${LDAP_OBJS}'
+	ldap_cflags='${LDAP_CFLAGS}'
+	ldap_targets='${LDAP_TARGETS}'
 	;;
 *)	ldap_includes=
 	ldap_libs=
@@ -22043,10 +22050,10 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_POSTGRESQL 1
 _ACEOF
 
-	postgresql_srcs='$(POSTGRESQL_SRCS)'
-	postgresql_objs='$(POSTGRESQL_OBJS)'
-	postgresql_cflags='$(POSTGRESQL_CFLAGS)'
-	postgresql_targets='$(POSTGRESQL_TARGETS)'
+	postgresql_srcs='${POSTGRESQL_SRCS}'
+	postgresql_objs='${POSTGRESQL_OBJS}'
+	postgresql_cflags='${POSTGRESQL_CFLAGS}'
+	postgresql_targets='${POSTGRESQL_TARGETS}'
 	;;
 *)	postgresql_includes=
 	postgresql_libs=
@@ -23973,6 +23980,74 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+### sanity check whether OpenSSL is really usable or not
+
+CPPFLAGS_SAVE="$CPPFLAGS"
+LIBS_SAVE="$LIBS"
+CPPFLAGS="${openssl_includes} $CPPFLAGS_SAVE"
+# -R is not portable without libtool, and not necessary for AC_TRY_LINK
+LIBS="`echo ${openssl_libs} | sed 's/-R[^ ]*//g'` $LIBS_SAVE"
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <openssl/evp.h>
+int
+main ()
+{
+
+EVP_MD_CTX md_ctx;
+EVP_MD *md_type = EVP_get_digestbyname("sha1");
+
+EVP_DigestInit(&md_ctx, md_type);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+  { { echo "$as_me:$LINENO: error: OpenSSL cannot be linked with \"${openssl_includes} ${openssl_libs}\" options, aborted" >&5
+echo "$as_me: error: OpenSSL cannot be linked with \"${openssl_includes} ${openssl_libs}\" options, aborted" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+CPPFLAGS="$CPPFLAGS_SAVE"
+LIBS="$LIBS_SAVE"
 
 ###### Checks for system services.
 # empty for now
