regen
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@732 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -949,7 +949,7 @@ EOF
 if { (eval echo configure:950: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   
-		echo "using \"${ldflag}\" to specify runtime shlib path"
+		echo "$ac_t""using \"${ldflag}\" to specify runtime shlib path" 1>&6
 		ld_rpath_flag="$ldflag"
 		break
 	
@@ -1086,7 +1086,7 @@ done
 
 
 if test x"${ac_cv_header_stdio_h}" != x"yes"; then
-	eval "echo preprocessor option error on: \"$ac_cpp\""
+	echo "$ac_t"""echo preprocessor option error on: \"$ac_cpp\""" 1>&6
 	#exit 1
 fi
 
@@ -1202,35 +1202,44 @@ openssl_cflags='$(OPENSSL_CFLAGS)'
 if test "${with_openldap+set}" = set; then
   withval="$with_openldap"
   with_openldap="${withval}"
- ldap_includedir=${with_openldap}/include
- ldap_libdir=${with_openldap}/lib
- ldap_includes=""
- ldap_libs="-lldap -llber"
- if test x"${with_openldap}" != x"/usr"; then
-   ldap_includes="-I${ldap_includedir} ${ldap_includes}"
-   ldap_libs="-L${ldap_libdir} ${ldap_libs}"
-   if test x"${ld_rpath_flag}" != x; then
-     ldap_libs="${ld_rpath_flag}${ldap_libdir} ${ldap_libs}"
-   fi
- fi
- ldap_srcs='$(LDAP_SRCS)'
- ldap_objs='$(LDAP_OBJS)'
- ldap_subdirs='$(LDAP_SUBDIRS)'
- ldap_cflagss='$(LDAP_CFLAGS)'
 
 else
   with_openldap=
- ldap_includedir=
- ldap_libdir=
- ldap_includes=
- ldap_libs=
- ldap_srcs=
- ldap_objs=
- ldap_subdirs=
- ldap_cflags=
 
 fi
 
+
+openldap_found=
+if test x"${with_openldap}" = x -o x"${with_openldap}" = x"yes"; then
+  for d in /usr/local/openldap /usr/local /usr/pkg /usr
+  do
+    if test -f $d/include/ldap.h; then
+	with_openldap=$d
+	echo "$ac_t""using \"${d}\" as openldap root directory" 1>&6
+	openldap_found=yes
+	break
+    fi
+  done
+  if test x"${openldap_found}" != x"yes"; then
+	{ echo "configure: error: openldap is not found, aborted" 1>&2; exit 1; }
+  fi
+fi
+
+ldap_includedir=${with_openldap}/include
+ldap_libdir=${with_openldap}/lib
+ldap_includes=""
+ldap_libs="-lldap -llber"
+if test x"${with_openldap}" != x"/usr"; then
+  ldap_includes="-I${ldap_includedir} ${ldap_includes}"
+  ldap_libs="-L${ldap_libdir} ${ldap_libs}"
+  if test x"${ld_rpath_flag}" != x; then
+    ldap_libs="${ld_rpath_flag}${ldap_libdir} ${ldap_libs}"
+  fi
+fi
+ldap_srcs='$(LDAP_SRCS)'
+ldap_objs='$(LDAP_OBJS)'
+ldap_subdirs='$(LDAP_SUBDIRS)'
+ldap_cflagss='$(LDAP_CFLAGS)'
 
 # OpenLDAP since 2.x calls res_query() and dn_expand(), if dnssrv is
 # configured, and DNS resolver library doesn't belongs to libc on some
@@ -1238,18 +1247,17 @@ fi
 # But we cannot blindly link libresolv, because it may change behaviour
 # of gethostbyname() and friends.
 
-if test x"${with_openldap}" != x; then
-
 CPPFLAGS_SAVE="$CPPFLAGS"
 LIBS_SAVE="$LIBS"
 
+openldap_found=
 for extra_lib in "" "-lresolv" "-lbind"; do
 
 CPPFLAGS="$CPPFLAGS_SAVE ${ldap_includes}"
 LIBS="$LIBS_SAVE ${ldap_libs} ${extra_lib}"
 
 cat > conftest.$ac_ext <<EOF
-#line 1253 "configure"
+#line 1261 "configure"
 #include "confdefs.h"
 
 #include <lber.h>
@@ -1260,13 +1268,14 @@ int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:1264: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1272: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   
 	if test x"${extra_lib}" != x; then
-		echo "using ${extra_lib} for LDAP"
+		echo "$ac_t""using ${extra_lib} for LDAP" 1>&6
 		ldap_libs="${ldap_libs} ${extra_lib}"
 	fi
+	openldap_found=yes
 	break
 
 else
@@ -1276,11 +1285,12 @@ fi
 rm -f conftest*
 
 done
+if test x"${openldap_found}" != x"yes"; then
+	{ echo "configure: error: openldap is not found, aborted" 1>&2; exit 1; }
+fi
 
 CPPFLAGS="$CPPFLAGS_SAVE"
 LIBS="$LIBS_SAVE"
-
-fi # with_openldap
 
 
 
@@ -1325,18 +1335,31 @@ if test "${with_globus+set}" = set; then
  globus_includedir='$(globus_location)/include/$(globus_flavor)'
  globus_libdir='$(globus_location)/lib'
  globus_includes='-I$(globus_includedir)'
- echo $ac_n "checking globus library names""... $ac_c" 1>&6
-echo "configure:1330: checking globus library names" >&5
+
+ cfgmhtmp=/tmp/cfgmh$$
  # $GLOBUS_LOCATION is needed to make globus-makefile-header work
  GLOBUS_LOCATION=${globus_location}; export GLOBUS_LOCATION
+ echo $ac_n "checking globus library names""... $ac_c" 1>&6
+echo "configure:1344: checking globus library names" >&5
+ if	case ${globus_shared} in
+	yes)	${globus_location}/bin/globus-makefile-header         -flavor=${globus_flavor} globus_gssapi_gsi;;
+	*)	${globus_location}/bin/globus-makefile-header -static -flavor=${globus_flavor} globus_gssapi_gsi;;
+	esac > $cfgmhtmp
+ then
+	echo "$ac_t""done" 1>&6
+ else
+	rm -f $cfgmhtmp
+	{ echo "configure: error: failed to call globus-makefile-header, aborted" 1>&2; exit 1; }
+ fi
+ globus_gssapi_libs=`sed -n '/^GLOBUS_PKG_LIBS *=/s///p' $cfgmhtmp`
+ rm -f $cfgmhtmp
  case ${globus_shared} in
- yes)	globus_gssapi_libs='-L$(globus_libdir) '"`${globus_location}/bin/globus-makefile-header -flavor=${globus_flavor} globus_gssapi_gsi | sed -n '/^GLOBUS_PKG_LIBS *=/s///p'`"
+ yes)	globus_gssapi_libs='-L$(globus_libdir) '"$globus_gssapi_libs"
 	if test x"${ld_rpath_flag}" != x; then
 	    globus_gssapi_libs="${ld_rpath_flag}"'$(globus_libdir)'" ${globus_gssapi_libs}"
 	fi;;
- *)	globus_gssapi_libs=`${globus_location}/bin/globus-makefile-header -static -flavor=${globus_flavor} globus_gssapi_gsi | sed -n '/^GLOBUS_PKG_LIBS *=/s///p'`;;
  esac
- echo "$ac_t""done" 1>&6
+
  globus_srcs='$(GLOBUS_SRCS)'
  globus_objs='$(GLOBUS_OBJS)'
  globus_subdirs='$(GLOBUS_SUBDIRS)'
@@ -1510,14 +1533,14 @@ fi
 
 
 echo $ac_n "checking whether byte ordering is bigendian""... $ac_c" 1>&6
-echo "configure:1514: checking whether byte ordering is bigendian" >&5
+echo "configure:1537: checking whether byte ordering is bigendian" >&5
 if eval "test \"`echo '$''{'ac_cv_c_bigendian'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_cv_c_bigendian=unknown
 # See if sys/param.h defines the BYTE_ORDER macro.
 cat > conftest.$ac_ext <<EOF
-#line 1521 "configure"
+#line 1544 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1528,11 +1551,11 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1532: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1555: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   # It does; now see whether it defined to BIG_ENDIAN or not.
 cat > conftest.$ac_ext <<EOF
-#line 1536 "configure"
+#line 1559 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1543,7 +1566,7 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1547: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1570: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_bigendian=yes
 else
@@ -1563,7 +1586,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1567 "configure"
+#line 1590 "configure"
 #include "confdefs.h"
 main () {
   /* Are we little or big endian?  From Harbison&Steele.  */
@@ -1576,7 +1599,7 @@ main () {
   exit (u.c[sizeof (long) - 1] == 1);
 }
 EOF
-if { (eval echo configure:1580: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1603: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_c_bigendian=no
 else
@@ -1601,7 +1624,7 @@ fi
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&6
-echo "configure:1605: checking size of long" >&5
+echo "configure:1628: checking size of long" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1609,7 +1632,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1613 "configure"
+#line 1636 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1620,7 +1643,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1624: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1647: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1640,7 +1663,7 @@ EOF
 
 
 echo $ac_n "checking size of long long""... $ac_c" 1>&6
-echo "configure:1644: checking size of long long" >&5
+echo "configure:1667: checking size of long long" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_long_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1648,7 +1671,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1652 "configure"
+#line 1675 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1659,7 +1682,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1663: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1686: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long_long=`cat conftestval`
 else
@@ -1683,17 +1706,17 @@ for ac_hdr in inttypes.h shadow.h crypt.h machine/endian.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1687: checking for $ac_hdr" >&5
+echo "configure:1710: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1692 "configure"
+#line 1715 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1697: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1720: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1723,12 +1746,12 @@ done
 for ac_func in poll pwrite snprintf gethostbyname2 getpassphrase setlogin strtoll strtoq setrlimit daemon getloadavg
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1727: checking for $ac_func" >&5
+echo "configure:1750: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1732 "configure"
+#line 1755 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1751,7 +1774,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1755: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1778: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1777,7 +1800,7 @@ done
 
 
 echo $ac_n "checking for gethostname in -lnsl""... $ac_c" 1>&6
-echo "configure:1781: checking for gethostname in -lnsl" >&5
+echo "configure:1804: checking for gethostname in -lnsl" >&5
 ac_lib_var=`echo nsl'_'gethostname | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1785,7 +1808,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lnsl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1789 "configure"
+#line 1812 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1796,7 +1819,7 @@ int main() {
 gethostname()
 ; return 0; }
 EOF
-if { (eval echo configure:1800: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1823: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1824,7 +1847,7 @@ else
 fi
 
 echo $ac_n "checking for socket in -lsocket""... $ac_c" 1>&6
-echo "configure:1828: checking for socket in -lsocket" >&5
+echo "configure:1851: checking for socket in -lsocket" >&5
 ac_lib_var=`echo socket'_'socket | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1832,7 +1855,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lsocket  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1836 "configure"
+#line 1859 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1843,7 +1866,7 @@ int main() {
 socket()
 ; return 0; }
 EOF
-if { (eval echo configure:1847: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1870: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1871,7 +1894,7 @@ else
 fi
 
 echo $ac_n "checking for crypt in -lcrypt""... $ac_c" 1>&6
-echo "configure:1875: checking for crypt in -lcrypt" >&5
+echo "configure:1898: checking for crypt in -lcrypt" >&5
 ac_lib_var=`echo crypt'_'crypt | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1879,7 +1902,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcrypt  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1883 "configure"
+#line 1906 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1890,7 +1913,7 @@ int main() {
 crypt()
 ; return 0; }
 EOF
-if { (eval echo configure:1894: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1917: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1918,7 +1941,7 @@ else
 fi
 
 echo $ac_n "checking for cuserid in -lcompat""... $ac_c" 1>&6
-echo "configure:1922: checking for cuserid in -lcompat" >&5
+echo "configure:1945: checking for cuserid in -lcompat" >&5
 ac_lib_var=`echo compat'_'cuserid | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1926,7 +1949,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcompat  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1930 "configure"
+#line 1953 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1937,7 +1960,7 @@ int main() {
 cuserid()
 ; return 0; }
 EOF
-if { (eval echo configure:1941: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1964: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1965,7 +1988,7 @@ else
 fi
 
 echo $ac_n "checking for basename in -lgen""... $ac_c" 1>&6
-echo "configure:1969: checking for basename in -lgen" >&5
+echo "configure:1992: checking for basename in -lgen" >&5
 ac_lib_var=`echo gen'_'basename | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1973,7 +1996,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lgen  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1977 "configure"
+#line 2000 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1984,7 +2007,7 @@ int main() {
 basename()
 ; return 0; }
 EOF
-if { (eval echo configure:1988: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2011: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2014,7 +2037,7 @@ fi
 
 
 cat > conftest.$ac_ext <<EOF
-#line 2018 "configure"
+#line 2041 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -2025,7 +2048,7 @@ int i = sys_nerr;
 
 ; return 0; }
 EOF
-if { (eval echo configure:2029: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2052: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ax_cv_have_sys_nerr=yes
 else
@@ -2044,7 +2067,7 @@ fi
 
 
 cat > conftest.$ac_ext <<EOF
-#line 2048 "configure"
+#line 2071 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -2059,7 +2082,7 @@ rv = getpwnam_r("root", pwd, buffer, sizeof buffer, &pwd);
 
 ; return 0; }
 EOF
-if { (eval echo configure:2063: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2086: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ax_cv_have_getpwnam_r=yes
 else
@@ -2078,7 +2101,7 @@ fi
 
 
 cat > conftest.$ac_ext <<EOF
-#line 2082 "configure"
+#line 2105 "configure"
 #include "confdefs.h"
 
 #include <shadow.h>
@@ -2092,7 +2115,7 @@ rv = getspnam_r("root", sp, buffer, sizeof buffer, &sp);
 
 ; return 0; }
 EOF
-if { (eval echo configure:2096: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2119: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ax_cv_have_getspnam_r=yes
 else
@@ -2111,7 +2134,7 @@ fi
 
 
 cat > conftest.$ac_ext <<EOF
-#line 2115 "configure"
+#line 2138 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -2126,7 +2149,7 @@ rv = bind(s, &addr, len);
 
 ; return 0; }
 EOF
-if { (eval echo configure:2130: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2153: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   ax_cv_have_socklen_t=yes
 else
@@ -2141,7 +2164,7 @@ if test "$ax_cv_have_socklen_t" = no; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 2145 "configure"
+#line 2168 "configure"
 #include "confdefs.h"
 
 # include <sys/types.h>
@@ -2159,7 +2182,7 @@ else
   }
   
 EOF
-if { (eval echo configure:2163: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2186: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ax_cv_socklen_t=int
 else
