regen
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@2344 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20216,6 +20216,9 @@ fi
 
 
 
+# sanity check for OpenSSL is deferred, because ${openssl_includes}
+# and ${openssl_lib} may be overrided by Globus autoconfiguration.
+
 ###
 ### --with-globus=GLOBUS_ROOT --with-globus-flavor=FLAVOR -with-globus-static
 ###
@@ -23898,6 +23901,74 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+### sanity check whether OpenSSL is really usable or not
+
+CPPFLAGS_SAVE="$CPPFLAGS"
+LIBS_SAVE="$LIBS"
+CPPFLAGS="${openssl_includes} $CPPFLAGS_SAVE"
+# -R is not portable without libtool, and not necessary for AC_TRY_LINK
+LIBS="`echo ${openssl_libs} | sed 's/-R[^ ]*//g'` $LIBS_SAVE"
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <openssl/evp.h>
+int
+main ()
+{
+
+EVP_MD_CTX md_ctx;
+EVP_MD *md_type = EVP_get_digestbyname("sha1");
+
+EVP_DigestInit(&md_ctx, md_type);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+  { { echo "$as_me:$LINENO: error: OpenSSL cannot be linked with \"${openssl_includes} ${openssl_libs}\" options, aborted" >&5
+echo "$as_me: error: OpenSSL cannot be linked with \"${openssl_includes} ${openssl_libs}\" options, aborted" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+CPPFLAGS="$CPPFLAGS_SAVE"
+LIBS="$LIBS_SAVE"
 
 ###### Checks for system services.
 # empty for now
