docker/dev: add SASL related authentication to authconfig
XXX: building jwt-agent while docker build fails with
go: golang.org/x/crypto@v0.0.0-20220722155217-630584e8d5aa: Get
"https://proxy.golang.org/golang.org/x/crypto/@v/v0.0.0-20220722155217-630584e8d5aa.info":
dial tcp: lookup proxy.golang.org on 8.8.4.4:53: read udp
172.17.0.2:40024->8.8.4.4:53: i/o timeout

building at "make shell" works though

diff --git a/docker/dev/common/authconfig b/docker/dev/common/authconfig
--- a/docker/dev/common/authconfig
+++ b/docker/dev/common/authconfig
@@ -42,8 +42,24 @@ usage()
 	echo >&2 "	tls_client_certificate"
 	echo >&2 "	gsi"
 	echo >&2 "	gsi_auth"
+	echo >&2 "	sasl_auth"
+	echo >&2 "	sasl"
+	echo >&2 "	sasl_auth.anonymous"
+	echo >&2 "	sasl_auth.login"
+	echo >&2 "	sasl_auth.plain"
+	echo >&2 "	sasl_auth.xoauth2"
+	echo >&2 "	sasl.anonymous"
+	echo >&2 "	sasl.login"
+	echo >&2 "	sasl.plain"
+	echo >&2 "	sasl.xoauth2"
 	echo >&2 "	kerberos"
 	echo >&2 "	kerberos_auth"
+	echo >&2 "(*) default:" "--client-server sharedsecret" \
+				"--server-server all"
+	echo >&2 "(*) sasl is allowed only for client authentication,"
+	echo >&2 "    thus, use setting like the following:"
+	echo >&2 "	${progname} --client-server sasl.plain" \
+				   "--server-server tls_client_certificate"
 	exit 2
 }
 
@@ -55,6 +71,11 @@ auth_method_check()
 	sharedsecret) :;;
 	tls_sharedsecret|tls_client_certificate) ;;
 	gsi|gsi_auth) ;;
+	sasl|sasl_auth) ;;
+	sasl.anonymous|sasl_auth.anonymous) ;;
+	sasl.login|sasl_auth.login) ;;
+	sasl.plain|sasl_auth.plain) ;;
+	sasl.xoauth2|sasl_auth.xoauth2) ;;
 	kerberos|kerberos_auth) ;;
 	*)	echo >&2 "${progname}: unknown auth_method <${auth_method}>"
 		usage;;
@@ -81,10 +102,19 @@ gen_auth_method()
 			echo "auth enable gsi ${hostname}"
 			echo "auth enable gsi_auth ${hostname}"
 		fi
+		if $sasl_available; then
+			echo "auth enable sasl ${hostname}"
+			echo "auth enable sasl_auth ${hostname}"
+		fi
 		if $krb_available; then
 			echo "auth enable kerberos ${hostname}"
 			echo "auth enable kerberos_auth ${hostname}"
 		fi
+		;;
+	sasl_auth.*)
+		echo "auth enable sasl_auth ${hostname}"
+		;;
+	sasl.*)	echo "auth enable sasl ${hostname}"
 		;;
 	*)	echo "auth enable ${auth_method} ${hostname}"
 		;;
@@ -119,6 +149,35 @@ gen_auth_config()
 		all)
 			gen_auth_method '*' "${auth_method}"
 			;;
+		esac
+	) >>"${auth_config_dir}/${config_name}.conf"
+}
+
+gen_auth_sasl_config()
+{
+	auth_method=$1
+	sasl_mech=$(echo "${auth_method}" | sed 's/sasl[_a-z]*//')
+	config_name=auth-client.sasl
+	(
+		case ${sasl_mech} in
+		''|.|.plain)
+			echo "sasl_mechanisms PLAIN"
+			echo "include .gfarm2rc.passwd"
+			;;
+		.login)
+			echo "sasl_mechanisms LOGIN"
+			echo "include .gfarm2rc.passwd"
+			;;
+		.anonymous)
+			echo "sasl_mechanisms ANONYMOUS"
+			echo "sasl_user dummy_user"
+			;;
+		.xoauth2)
+			echo "sasl_mechanisms XOAUTH2"
+			echo "sasl_user REPLACE-THIS-BY-YOUR-OAUTH-ID"
+			;;
+		*)	echo >&2 "ERROR: unknown sasl_mechanisms <$sasl_mech>"
+			exit 2;;
 		esac
 	) >>"${auth_config_dir}/${config_name}.conf"
 }
@@ -235,6 +294,9 @@ kerberos*)
 	gfuser_4th_needs_krb_principal=true
 	gfsd_needs_host_cred=true
 	;;
+sasl*)
+	gfsd_needs_service_cred=true
+	;;
 esac
 case ${client_gfsd} in
 tls_*|gsi*)
@@ -245,9 +307,12 @@ kerberos*)
 	gfuser_4th_needs_krb_principal=true
 	gfsd_needs_host_cred=true
 	;;
+sasl*)
+	gfsd_needs_service_cred=true
+	;;
 esac
 case ${gfsd_gfmd} in
-tls_*|gsi*)
+tls_*|gsi*|sasl*)
 	gfsd_needs_service_cred=true
 	;;
 kerberos*)
@@ -255,7 +320,7 @@ kerberos*)
 	;;
 esac
 case ${gfsd_gfsd} in
-tls_*|gsi*)
+tls_*|gsi*|sasl*)
 	gfsd_needs_service_cred=true
 	;;
 kerberos*)
@@ -293,6 +358,14 @@ then
 	gsi_available=true
 else
 	gsi_available=false
+fi
+
+if gfstatus 2>/dev/null | grep '^client auth sasl ' |
+		grep ': available' >/dev/null
+then
+	sasl_available=true
+else
+	sasl_available=false
 fi
 
 if gfstatus 2>/dev/null | grep '^client auth kerberos' |
@@ -360,13 +433,37 @@ if ! ${gfsd_needs_host_cred}; then
 fi
 
 clear_auth_config auth-client
+clear_auth_config auth-client.sasl
 if [ "${client_gfsd}" = "${client_gfmd}" ]; then
 	gen_auth_config auth-client "all" "${client_gfsd}"
+	case ${client_gfsd} in
+	sasl*)	gen_auth_sasl_config "${client_gfsd}";;
+	esac
 else
 	gen_auth_config auth-client gfmd "${client_gfmd}"
 	gen_auth_config auth-client gfsd "${client_gfsd}"
+	case "${client_gfmd}/${client_gfsd}" in
+	sasl*/sasl*)
+		gfmd_sasl_mech=$(echo "client_gfmd" | sed 's/sasl[_a-z]*//')
+		gfsd_sasl_mech=$(echo "client_gfsd" | sed 's/sasl[_a-z]*//')
+		if [ "gfmd_sasl_mech" != "gfsd_sasl_mech" ]; then
+			echo >&2 "ERROR: mismatch between" \
+				"gfmd sasl_mech=<$gfmd_sasl_mech>" and \
+				"gfsd sasl_mech=<$gfsd_sasl_mech>" 
+			exit 2
+		fi
+		;;
+	esac
+	case ${client_gfmd} in
+	sasl*)	gen_auth_sasl_config "${client_gfmd}";;
+	*)	case ${client_gfsd} in
+		sasl*)	gen_auth_sasl_config "${client_gfsd}";;
+		esac;;
+	esac
 fi
 if ! ${gfsd_needs_host_cred}; then
+	# /usr/local/etc/gfarm2.conf on gfsd hosts is used by
+	# both gfsd and clients, but that's OK in this case.
 	gen_cred_config auth-client
 fi
 
