rc.subr is moved from /usr/local/etc to /etc on FreeBSD-5.X
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@2208 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/config-gfarm/sysdep/freebsd/gfarm-slapd.in b/gftool/config-gfarm/sysdep/freebsd/gfarm-slapd.in
--- a/gftool/config-gfarm/sysdep/freebsd/gfarm-slapd.in
+++ b/gftool/config-gfarm/sysdep/freebsd/gfarm-slapd.in
@@ -16,8 +16,14 @@
 #
 # See slapd(8) for more flags
 #
-
-. "/usr/local/etc/rc.subr"
+if [ -f /usr/local/etc/rc.subr ]; then
+	. /usr/local/etc/rc.subr
+elif [ -f /etc/rc.subr ]; then
+	. /etc/rc.subr
+else
+	echo "$0: abort: rc.subr not found"
+	exit 2
+fi
 
 FILE=gfarm-slapd
 CONF="@config_gfarm_slapd_config@"
diff --git a/gftool/config-gfarm/sysdep/freebsd/gfmd.in b/gftool/config-gfarm/sysdep/freebsd/gfmd.in
--- a/gftool/config-gfarm/sysdep/freebsd/gfmd.in
+++ b/gftool/config-gfarm/sysdep/freebsd/gfmd.in
@@ -14,7 +14,14 @@
 # gfmd_flags (str):        Set to "" by default.
 #                             Extra flags passed to start command
 #
-. "/usr/local/etc/rc.subr"
+if [ -f /usr/local/etc/rc.subr ]; then
+	. /usr/local/etc/rc.subr
+elif [ -f /etc/rc.subr ]; then
+	. /etc/rc.subr
+else
+	echo "$0: abort: rc.subr not found"
+	exit 2
+fi
 
 CONF="@config_gfarm_gfarm_config@"
 OPTIONS="@config_gfarm_gfmd_option@"
