merge changes in gfarm_v2/branches/2.2.0 into the main trunk.
i.e. apply the following changes:
r4105 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4105
r4106 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4106
r4107 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4107
r4108 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4108
r4109 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4109
r4110 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4110
r4111 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4111
r4112 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4112
r4113 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4113
r4114 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4114
r4115 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4115
r4116 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4116
r4117 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4117
r4118 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4118
r4121 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4121
r4122 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4122
r4123 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4123
r4124 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4124
r4125 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4125
r4126 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4126
r4127 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4127
r4128 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4128
r4132 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4132
r4134 - http://gfarm.svn.sourceforge.net/viewvc/gfarm?view=rev&revision=4134


git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/trunk@4139 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/gfdump/gfdump.postgresql.in b/gftool/gfdump/gfdump.postgresql.in
--- a/gftool/gfdump/gfdump.postgresql.in
+++ b/gftool/gfdump/gfdump.postgresql.in
@@ -12,9 +12,9 @@ usage() {
 #	CONFIG_DIR	configuration directory	[$PREFIX/etc]
 #	DATA_DIR	data directory of pgsql	[$PREFIX/var/gfarm-pgsql]
 
-PREFIX=@prefix@
-: ${CONFIG_DIR:="$PREFIX/etc"}
-: ${DATA_DIR:="$PREFIX/var/gfarm-pgsql"}
+prefix=@prefix@
+: ${CONFIG_DIR:="@sysconfdir@"}
+: ${DATA_DIR:="@localstatedir@/gfarm-pgsql"}
 GFMDCONF=$CONFIG_DIR/gfmd.conf
 DUMPF=db.out
 MODE=UNKNOWN
@@ -77,14 +77,29 @@ if [ X$MODE = XRESTORE ]; then
 		err "$DUMPF: database dump file not exist"
 fi
 
-# XXX - always overwrite ~/.pgpass
-PGPASS=~/.pgpass
-touch $PGPASS || err "$PGPASS: cannot create"
-chmod 0600 $PGPASS || err "$PGPASS: cannot change mode"
-cat > $PGPASS <<EOF
-$HOST:$PORT:$DBNAME:$USER:$PASSWD
-*:$PORT:$DBNAME:$ADMIN_USER:$ADMIN_PASSWD
-EOF
+# $LINE is appended to $FILE only if $LINE is not included in $FILE
+update_file()
+{
+	FILE="$1"
+	LINE="$2"
+
+	if [ ! -f $FILE ]; then
+		echo $LINE > $FILE
+	elif ! grep "^$LINE$" $FILE > /dev/null; then
+		echo $LINE >> $FILE
+	fi
+}
+
+# update $HOME/.pgpass
+PGPASS=$HOME/.pgpass
+if [ ! -f $PGPASS ]; then
+	touch $PGPASS || err "$PGPASS: cannot create"
+	chmod 0600 $PGPASS || err "$PGPASS: cannot change mode"
+fi
+# disable path expansion
+set -f
+update_file $PGPASS "$HOST:$PORT:$DBNAME:$USER:$PASSWD"
+update_file $PGPASS "localhost:$PORT:$DBNAME:$ADMIN_USER:$ADMIN_PASSWD"
 
 case $MODE in
     DUMP)
