do not overwrite .pgpass, but update it if required.  suggested by soda-san
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.1.2@4121 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/gfdump/gfdump.postgresql.in b/gftool/gfdump/gfdump.postgresql.in
--- a/gftool/gfdump/gfdump.postgresql.in
+++ b/gftool/gfdump/gfdump.postgresql.in
@@ -77,14 +77,29 @@ if [ X$MODE = XRESTORE ]; then
 		err "$DUMPF: database dump file not exist"
 fi
 
-# XXX - always overwrite ~/.pgpass
-PGPASS=~/.pgpass
-touch $PGPASS || err "$PGPASS: cannot create"
-chmod 0600 $PGPASS || err "$PGPASS: cannot change mode"
-cat > $PGPASS <<EOF
-$HOST:$PORT:$DBNAME:$USER:$PASSWD
-*:$PORT:$DBNAME:$ADMIN_USER:$ADMIN_PASSWD
-EOF
+# $LINE is appended to $FILE only if $LINE is not included in $FILE
+update_file()
+{
+	FILE="$1"
+	LINE="$2"
+
+	if [ ! -f $FILE ]; then
+		echo $LINE > $FILE
+	elif ! grep $LINE $FILE > /dev/null; then
+		echo $LINE >> $FILE
+	fi
+}
+
+# update $HOME/.pgpass
+PGPASS=$HOME/.pgpass
+if [ ! -f $PGPASS ]; then
+	touch $PGPASS || err "$PGPASS: cannot create"
+	chmod 0600 $PGPASS || err "$PGPASS: cannot change mode"
+fi
+# disable path expansion
+set -f
+update_file $PGPASS "$HOST:$PORT:$DBNAME:$USER:$PASSWD"
+update_file $PGPASS "localhost:$PORT:$DBNAME:$ADMIN_USER:$ADMIN_PASSWD"
 
 case $MODE in
     DUMP)
