cvs 20021101 upstream release.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@211 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/debian/gfarm-server.init b/debian/gfarm-server.init
--- a/debian/gfarm-server.init
+++ b/debian/gfarm-server.init
@@ -1,26 +1,45 @@
 #! /bin/sh
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/gfarmd
-NAME=gfarmd
-DESC="gfarm daemon"
+# gfarmd 
+DAEMON_GFARMD=/usr/sbin/gfarmd
+NAME_GFARMD=gfarmd
+DESC_GFARMD="gfarmd"
+# gfmd
+DAEMON_GFMD=/usr/sbin/gfmd
+NAME_GFMD=gfmd
+DESC_GFMD="gfmd"
 
-test -f $DAEMON || exit 0
-
+test -f $DAEMON_GFARMD || exit 0
+test -f $DAEMON_GFMD || exit 0
 set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	start-stop-daemon --start --quiet --exec $DAEMON
-	echo "$NAME."
+	# gfarmd
+	echo -n "Starting $DESC_GFARMD: "
+	start-stop-daemon --start --quiet --exec $DAEMON_GFARMD
+	echo "$NAME_GFARMD."
+
+	# gfmd
+	echo -n "Starting $DESC_GFMD: "
+	start-stop-daemon --start --quiet --exec $DAEMON_GFMD
+	echo "$NAME_GFMD."
 	;;
   stop)
-	echo -n "Stopping $DESC: "
-#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
+	# gfarmd
+	echo -n "Stopping $DESC_GFARMD: "
+#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON_GFARMD
         # to avoid post-installation script abort on non-zero return value.
-	echo `killall $NAME`&>/dev/null 
-	echo "$NAME."
+	echo `killall $NAME_GFARMD`&>/dev/null 
+	echo "$NAME_GFARMD."
+
+	# gfmd
+	echo -n "Stopping $DESC_GFMD: "
+#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON_GFMD
+        # to avoid post-installation script abort on non-zero return value.
+	echo `killall $NAME_GFMD`&>/dev/null 
+	echo "$NAME_GFMD."
 	;;
   #reload)
 	#
@@ -30,9 +49,9 @@ case "$1" in
 	#	If the daemon responds to changes in its config file
 	#	directly anyway, make this a do-nothing entry.
 	#
-	# echo "Reloading $DESC configuration files."
+	# echo "Reloading $DESC_GFARMD configuration files."
 	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
-	#	/var/run/$NAME.pid --exec $DAEMON
+	#	/var/run/$NAME_GFARMD.pid --exec $DAEMON_GFARMD
   #;;
   restart|force-reload)
 	#
@@ -40,16 +59,27 @@ case "$1" in
 	#	option to the "reload" entry above. If not, "force-reload" is
 	#	just the same as "restart".
 	#
-	echo -n "Restarting $DESC: "
-#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON
+
+        # gfarmd
+	echo -n "Restarting $DESC_GFARMD: "
+#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON_GFARMD
         # to avoid post-installation script abort on non-zero return value.
-	echo `killall $NAME`&>/dev/null 
+	echo `killall $NAME_GFARMD`&>/dev/null 
 	sleep 1
-	start-stop-daemon --start --quiet --exec $DAEMON
-	echo "$NAME."
+	start-stop-daemon --start --quiet --exec $DAEMON_GFARMD
+	echo "$NAME_GFARMD."
+
+	# gfmd
+	echo -n "Restarting $DESC_GFMD: "
+#	start-stop-daemon --stop --oknodo --quiet --exec $DAEMON_GFMD
+        # to avoid post-installation script abort on non-zero return value.
+	echo `killall $NAME_GFMD`&>/dev/null 
+	sleep 1
+	start-stop-daemon --start --quiet --exec $DAEMON_GFMD
+	echo "$NAME_GFMD."
 	;;
   *)
-	N=/etc/init.d/$NAME
+	N="/etc/init.d/gfarm-server"
 	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $N {start|stop|restart|force-reload}" >&2
 	exit 1
