Add 'kill-gfmd-all' sub-command to 'gfservice'. 'gfservice' uses 'gfservice-timeout' script to start/stop/kill servers.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.5@8531 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/util/gfservice/gfservice-agent.in b/util/gfservice/gfservice-agent.in
--- a/util/gfservice/gfservice-agent.in
+++ b/util/gfservice/gfservice-agent.in
@@ -22,10 +22,13 @@ DEBUG=false
 SHARED_KEY_FILE="$HOME/.gfarm_shared_key"
 
 # gfservice plugin directory
-GFSERVICE_PLUGIN_PATH="@datadir@/gfarm/gfservice"
+GFSERVICE_PLUGIN_DIR="@datadir@/gfarm/gfservice"
 
 # Installation path of Globus Toolkit
 GLOBUS_LOCATION="@globus_location@"
+
+# Exitcode 'gfservice-timeout' returns in case of timeout.
+EXITCODE_TIMEOUT=124
 
 #
 # Output a debug message.
@@ -372,214 +375,6 @@ get_gfsd_status()
 	fi
 }
 
-#
-# Start PostgreSQL.
-#   TO DO: Don't execute $BACKEND_RC.  Use service_ctl instead.
-#
-start_pgsql()
-{
-	log_debug "start_pgsql: TIMEOUT=$1"
-
-	I=0
-	STARTED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$BACKEND_RC status > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			STARTED=true
-			break
-		fi
-		[ $I -eq 0 ] && $BACKEND_RC start > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STARTED != true ] && log_error "failed to start PostgreSQL"
-	log_debug "end start_pgsql"
-	return 0
-}
-
-#
-# Start gfmd.
-#   TO DO: Don't execute $GFMD_RC.  Use service_ctl instead.
-#
-start_gfmd()
-{
-	log_debug "start_gfmd: TIMEOUT=$1"
-
-	I=0
-	STARTED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFMD_RC status > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			STARTED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFMD_RC start > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STARTED != true ] && log_error "failed to start gfmd"
-	log_debug "end start_gfmd"
-	return 0
-}
-
-#
-# Start gfmd as a slave.
-#   TO DO: Don't execute $GFMD_RC.  Use service_ctl instead.
-#
-slavestart_gfmd()
-{
-	log_debug "slavestart_gfmd: TIMEOUT=$1"
-
-	I=0
-	STARTED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFMD_RC status > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			STARTED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFMD_RC slavestart > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STARTED != true ] && log_error "failed to start gfmd as a slave"
-	log_debug "end slavestart_gfmd"
-	return 0
-}
-
-#
-# Start gfsd.
-#   TO DO: Don't execute $GFSD_RC.  Use service_ctl instead.
-#
-start_gfsd()
-{
-	log_debug "start_gfsd: TIMEOUT=$1"
-
-	I=0
-	STARTED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFSD_RC status > /dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			STARTED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFSD_RC start > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STARTED != true ] && log_error "failed to start gfsd"
-	log_debug "end start_gfsd"
-	return 0
-}
-
-#
-# Stop PostgreSQL.
-#   TO DO: Don't execute $BACKEND_RC.  Use service_ctl instead.
-#
-stop_pgsql()
-{
-	log_debug "stop_pgsql: TIMEOUT=$1"
-
-	I=0
-	STOPPED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$BACKEND_RC status > /dev/null 2>&1
-		if [ $? -eq 3 -o $? -eq 127 ]; then
-			STOPPED=true
-			break
-		fi
-		[ $I -eq 0 ] && $BACKEND_RC stop > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STOPPED != true ] && log_error "failed to stop PostgreSQL"
-	log_debug "end stop_pgsql"
-	return 0
-}
-
-#
-# Stop gfmd.
-#   TO DO: Don't execute $GFMD_RC.  Use service_ctl instead.
-#
-stop_gfmd()
-{
-	log_debug "stop_gfmd: TIMEOUT=$1"
-
-	I=0
-	STOPPED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFMD_RC status > /dev/null 2>&1
-		if [ $? -eq 3 -o $? -eq 127 ]; then
-			STOPPED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFMD_RC stop > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STOPPED != true ] && log_error "failed to stop gfmd"
-	log_debug "end stop_gfmd"
-	return 0
-}
-
-#
-# Stop gfsd.
-#   TO DO: Don't execute $GFSD_RC.  Use service_ctl instead.
-#
-stop_gfsd()
-{
-	log_debug "stop_gfsd: TIMEOUT=$1"
-
-	I=0
-	STOPPED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFSD_RC status > /dev/null 2>&1
-		if [ $? -eq 3 -o $? -eq 127 ]; then
-			STOPPED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFSD_RC stop > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STOPPED != true ] && log_error "failed to stop gfsd"
-	log_debug "end stop_gfsd"
-	return 0
-}
-
-#
-# Kill gfmd.
-#   TO DO: Don't execute $GFMD_RC.  Use service_ctl instead.
-#
-kill_gfmd()
-{
-	log_debug "kill_gfmd: TIMEOUT=$1"
-
-	I=0
-	STOPPED=false
-	while [ "X$1" = Xno ] || [ $I -le "$1" ]; do
-		$GFMD_RC status > /dev/null 2>&1
-		if [ $? -eq 3 -o $? -eq 127 ]; then
-			STOPPED=true
-			break
-		fi
-		[ $I -eq 0 ] && $GFMD_RC kill > /dev/null 2>&1
-		sleep 1
-		I=`expr $I + 1`
-	done
-
-	[ $STOPPED != true ] && log_error "failed to kill gfmd"
-	log_debug "end kill_gfmd"
-	return 0
-}
-
 ######################################################################
 
 #
@@ -695,8 +490,9 @@ subcmd_start_backend_db()
 	log_debug "subcmd_start_backend_db"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_start_backend_db: timeout=$TIMEOUT"
-	start_pgsql $TIMEOUT
+	log_debug "subcmd_start_backend_db:" \
+		"execute gfservice-timeout $TIMEOUT $BACKEND_RC start"
+	gfservice-timeout $TIMEOUT $BACKEND_RC start > /dev/null 2>&1
 
 	log_debug "end subcmd_start_backend_db"
 }
@@ -710,8 +506,10 @@ subcmd_start_gfmd()
 	log_debug "subcmd_start_gfmd"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_start_gfmd: timeout=$TIMEOUT"
-	start_gfmd $TIMEOUT
+	log_debug "subcmd_start_gfmd:" \
+		"execute gfservice-timeout $TIMEOUT $GFMD_RC start"
+	gfservice-timeout $TIMEOUT $GFMD_RC start > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to start backend DB"
 
 	log_debug "subcmd_start_gfmd"
 }
@@ -725,9 +523,11 @@ subcmd_start_gfmd_master()
 	log_debug "subcmd_start_gfmd_master"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_start_gfmd_master: timeout=$TIMEOUT"
 	unset_conf $GFMD_CONF metadb_server_force_slave
-	start_gfmd $TIMEOUT
+	log_debug "subcmd_start_gfmd_master:" \
+		"execute gfservice-timeout $TIMEOUT $GFMD_RC start"
+	gfservice-timeout $TIMEOUT $GFMD_RC start > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to start gfmd"
 
 	log_debug "end subcmd_start_gfmd_master"
 }
@@ -741,8 +541,10 @@ subcmd_start_gfmd_slave()
 	log_debug "subcmd_start_gfmd_slave"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_start_gfmd_slave: timeout=$TIMEOUT"
-	slavestart_gfmd $TIMEOUT
+	log_debug "subcmd_start_gfmd_slave:" \
+		"execute gfservice-timeout $TIMEOUT $GFMD_RC slavestart"
+	gfservice-timeout $TIMEOUT $GFMD_RC slavestart > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to start gfmd"
 
 	log_debug "end subcmd_start_gfmd_slave"
 }
@@ -756,8 +558,10 @@ subcmd_start_gfsd()
 	log_debug "subcmd_start_gfsd"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_start_gfsd: timeout=$TIMEOUT"
-	start_gfsd $TIMEOUT
+	log_debug "subcmd_start_gfsd:" \
+		"execute gfservice-timeout $TIMEOUT $GFSD_RC start"
+	gfservice-timeout $TIMEOUT $GFSD_RC start > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to start gfsd"
 
 	log_debug "end subcmd_start_gfsd"
 }
@@ -771,8 +575,10 @@ subcmd_stop_backend_db()
 	log_debug "subcmd_stop_backend_db"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_stop_backend_db: timeout=$TIMEOUT"
-	stop_pgsql $TIMEOUT
+	log_debug "subcmd_stop_backend_db:" \
+		"execute gfservice-timeout $TIMEOUT $BACKEND_RC stop"
+	gfservice-timeout $TIMEOUT $BACKEND_RC stop > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to stop backend DB"
 
 	log_debug "end subcmd_stop_backend_db"
 }
@@ -786,8 +592,10 @@ subcmd_stop_gfmd()
 	log_debug "subcmd_stop_gfmd"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_stop_gfmd: timeout=$TIMEOUT"
-	stop_gfmd $TIMEOUT
+	log_debug "subcmd_stop_gfmd:" \
+		"execute gfservice-timeout $TIMEOUT $GFMD_RC stop"
+	gfservice-timeout $TIMEOUT $GFMD_RC stop > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to stop gfmd"
 
 	log_debug "end subcmd_stop_gfmd"
 }
@@ -801,8 +609,10 @@ subcmd_kill_gfmd()
 	log_debug "subcmd_kill_gfmd"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_kill_gfmd: timeout=$TIMEOUT"
-	kill_gfmd $TIMEOUT
+	log_debug "subcmd_kill_gfmd:" \
+		"execute gfservice-timeout $TIMEOUT $GFMD_RC kill"
+	gfservice-timeout $TIMEOUT $GFMD_RC kill > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to kill gfmd"
 
 	log_debug "end subcmd_kill_gfmd"
 }
@@ -816,8 +626,10 @@ subcmd_stop_gfsd()
 	log_debug "subcmd_stop_gfsd"
 
 	TIMEOUT=`get_param timeout || echo 'no'`
-	log_debug "subcmd_stop_gfsd: timeout=$TIMEOUT"
-	stop_gfsd $TIMEOUT
+	log_debug "subcmd_stop_gfsd:" \
+		"execute gfservice-timeout $TIMEOUT $GFSD_RC stop"
+	gfservice-timeout $TIMEOUT $GFSD_RC stop > /dev/null 2>&1
+	[ $? -eq $EXITCODE_TIMEOUT ] && log_error "failed to stop gfsd"
 
 	log_debug "end subcmd_stop_gfsd"
 }
@@ -1485,15 +1297,15 @@ gfcmd)
 *)
 	SUBCMD="`echo $SUBCMD | sed -e 's|::|/|g'`"
 	SUBCMD_FUNC="`basename $SUBCMD | sed -e 's|-|_|g'`"
-	if [ -f $GFSERVICE_PLUGIN_PATH/$SUBCMD ]; then
+	if [ -f $GFSERVICE_PLUGIN_DIR/$SUBCMD ]; then
 		log_debug "loading plugin: $SUBCMD"
-		. $GFSERVICE_PLUGIN_PATH/$SUBCMD
+		. $GFSERVICE_PLUGIN_DIR/$SUBCMD
 
 		DEFPEND_FILES="`${SUBCMD_FUNC}_agent_depends \
 			| sed -e 's|::|/|g'`"
 		for I in $DEFPEND_FILES; do
 			log_debug "loading plugin: $I"
-			. $GFSERVICE_PLUGIN_PATH/$I
+			. $GFSERVICE_PLUGIN_DIR/$I
 		done
 
 		subcmd_${SUBCMD_FUNC}_agent "$@"
