merge r7768 from the main trunk: add an option to gfservice(#564 Enhancement of gfservice):  * changed gfservice not to setup sharedkey with config-* sub command by default
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.6@7770 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/util/gfservice/gfservice.in b/util/gfservice/gfservice.in
--- a/util/gfservice/gfservice.in
+++ b/util/gfservice/gfservice.in
@@ -68,6 +68,7 @@ print_usage()
 	echo "  -d                debug mode"                     1>&2
 	echo "  -f <file>         specify the configuration file" 1>&2
 	echo "  -t <seconds>      specify the timeout period"     1>&2
+	echo "  -k                set up shared key in config-* sub-command" 1>&2
 }
 
 #
@@ -991,7 +992,7 @@ subcmd_config_gfarm()
 	#
 	# Create a new shared secret key.
 	#
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		exec_remote_host_gfcmd $HOSTID - gfkey -f \
 			-p $SHARED_KEY_VALIDITY_PERIOD
 		[ $? -ne 0 ] && log_error "gfkey failed"
@@ -1007,7 +1008,7 @@ subcmd_config_gfarm()
 	# Distribute a shared secret key from the gfmd host.
 	#
 	rm -f $TMP_FILE
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		exec_client_host_agent $HOSTID - backup-shared-key > $TMP_FILE
 		[ $? -ne 0 ] && log_error "gfservice backup-shared-key failed"
 		distribute_shared_key $TMP_FILE
@@ -1075,7 +1076,7 @@ subcmd_config_gfarm_master()
 	#
 	# Create a new shared secret key.
 	#
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		exec_remote_host_gfcmd $HOSTID - gfkey -f \
 			-p $SHARED_KEY_VALIDITY_PERIOD
 		[ $? -ne 0 ] && log_error "gfkey failed"
@@ -1091,7 +1092,7 @@ subcmd_config_gfarm_master()
 	# Distribute a shared secret key from the gfmd host.
 	#
 	rm -f $TMP_FILE
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		exec_client_host_agent $HOSTID - backup-shared-key > $TMP_FILE
 		[ $? -ne 0 ] && log_error "gfservice backup-shared-key failed"
 		distribute_shared_key $TMP_FILE
@@ -1214,7 +1215,7 @@ subcmd_config_gfarm_slave()
 	#
 	# Copy a shared secret key from the master gfmd host to the slave.
 	#
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		rm -f $TMP_FILE
 		exec_client_host_agent $MASTER - backup-shared-key \
 			> $TMP_FILE
@@ -1321,7 +1322,7 @@ subcmd_config_gfsd()
 	# Copy a shared secret key from gfmd1 to the gfsd host.
 	#
 	rm -f $TMP_FILE
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		rm -f $TMP_FILE
 		exec_client_host_agent gfmd1 - backup-shared-key \
 			> $TMP_FILE
@@ -1396,7 +1397,7 @@ subcmd_config_client()
 	# Copy a shared secret key from gfmd1 to the client host.
 	#
 	rm -f $TMP_FILE
-	if [ "X$AUTH_TYPE" = Xsharedsecret ]; then
+	if [ "X$AUTH_TYPE" = Xsharedsecret && X$SETUP_SHAREDKEY = Xtrue ]; then
 		rm -f $TMP_FILE
 		exec_client_host_agent gfmd1 - backup-shared-key \
 			> $TMP_FILE
@@ -1858,6 +1859,9 @@ while true; do
 		-t*)	TIMEOUT=`echo "X$OPT" | sed -e 's/^X-t//'`
 			OPT=
 			;;
+		-k)	SETUP_SHAREDKEY=true
+			OPT=
+			;;
 		*)	BAD_OPT=`echo "X$OPT" | sed -e 's/^X-\(.\).*$/\1/'`
 			echo "$0: invalid option -- '$BAD_OPT'" 1>&2
 			print_usage
@@ -1890,6 +1894,12 @@ fi
 if [ "X$TIMEOUT" != Xno ]; then
 	expr "$TIMEOUT" : '^[1-9][0-9]*$' > /dev/null 2>&1 || {
 		log_error "invalid timeout period $TIMEOUT"
+	}
+fi
+
+if [ X$SETUP_SHAREDKEY = Xtrue ]; then
+	expr $SUBCMD : '^config-.*' > /dev/null 2>&1 || {
+		log_error "'-k' option specified with invalid sub command"
 	}
 fi
 
