Apply r8209 (for trunk) to the 2.5 branch. (#696)
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.5@8215 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/systest/plugins/config_gfarm_update_r b/systest/plugins/config_gfarm_update_r
--- a/systest/plugins/config_gfarm_update_r
+++ b/systest/plugins/config_gfarm_update_r
@@ -14,8 +14,8 @@ subcmd_config_gfarm_update_r()
 	log_debug "subcmd_config_gfarm_update_r"
 
 	check_argc $# 0
-	check_gfmd_hostid $HOSTID
-	exec_gfmd_host_agent $HOSTID root config_gfarm_update_r "$@"
+	check_hostid gfmd $HOSTID
+	exec_remote_host_agent $HOSTID root config_gfarm_update_r "$@"
 	[ $? -ne 0 ] && log_error "gfservice config_gfarm_update_r failed"
 
 	log_debug "end subcmd_config_gfarm_update_r"
@@ -37,10 +37,17 @@ subcmd_config_gfarm_update_r_agent()
 {
 	log_debug "subcmd_config_gfarm_update_r_agent"
 
-	set_gfmd_params
-
-	config-gfarm-update --prefix $CONFIG_PREFIX -r --update
-	[ $? -ne 0 ] && log_error "gfjournal command failed"
+	if [ "X$CONFIG_PREFIX" = X ]; then
+		log_debug "subcmd_config_gfarm_update_r_agent: execute" \
+			config-gfarm-update -r --update
+		config-gfarm-update -r --update
+		[ $? -ne 0 ] && log_error "config-gfarm-update command failed"
+	else
+		log_debug "subcmd_config_gfarm_update_r_agent: execute" \
+			config-gfarm-update --prefix $CONFIG_PREFIX -r --update
+		config-gfarm-update --prefix $CONFIG_PREFIX -r --update
+		[ $? -ne 0 ] && log_error "config-gfarm-update command failed"
+	fi
 
 	log_debug "end subcmd_config_gfarm_update_r_agent"
 }
