merge r6918 and r6992 from the 2.5 branch - Fix #301 - config-gfarm-update -r cannot enable metadb replication - sequel to r6918 - journal directory name may include trailing space
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.5.7@6995 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/config-gfarm/config-gfarm-update.in b/gftool/config-gfarm/config-gfarm-update.in
--- a/gftool/config-gfarm/config-gfarm-update.in
+++ b/gftool/config-gfarm/config-gfarm-update.in
@@ -85,7 +85,7 @@ update_sanity()
 # from display_backend_params_$BACKEND_TYPE, but some may not.
 display_plain_param_backend_data_dir()
 {
-    echo     "metadata     directory    [-l]: $BACKEND_DATA_DIR"
+    echo     "metadata directory  [-l]: $BACKEND_DATA_DIR"
 }
 
 display_plain_param_backend_log_dir()
@@ -101,6 +101,14 @@ tf2yn()
     esac
 }
 
+tf2ed()
+{
+    case $1 in
+    true) echo enable;;
+    *)    echo disable;;
+    esac
+}
+
 display_params()
 {
     echo     "prefix [--prefix]: $CONFIG_PREFIX"
@@ -111,10 +119,9 @@ display_params()
     display_plain_params_backend_optional_$BACKEND_TYPE
 
     update_sanity
-    METADATA_REPLICATION_YN=`tf2yn $METADATA_REPLICATION`
-    echo "metadata replication       [-r]: $METADATA_REPLICATION_YN"
+    echo "metadata replication         [-r]: `tf2yn $METADATA_REPLICATION`"
     if $METADATA_REPLICATION; then
-        echo "metadata journal directory [-j]: $METADATA_JOURNAL_DIR"
+        echo "metadata journal directory   [-j]: $METADATA_JOURNAL_DIR"
     fi
     exit 0
 }
@@ -122,39 +129,31 @@ display_params()
 update_metadata_replication()
 {
     if $METADATA_REPLICATION; then
-	if $METADATA_REPLICATION1; then
-	    :
-	elif [ -e "$METADATA_JOURNAL_DIR/0000000000.gmj" ]; then
-	    echo >&2 "journal file already exists in $METADATA_JOURNAL_DIR."
-	    exit 1
-        fi
-        [ -d $METADATA_JOURNAL_DIR ] || mkdir -p $METADATA_JOURNAL_DIR
-        [ -e $METADATA_JOURNAL_DIR ] && chmod 700 $METADATA_JOURNAL_DIR
+	create_directory "$METADATA_JOURNAL_DIR"
+	chmod 700 "$METADATA_JOURNAL_DIR"
     fi
 
-    if [ X"$METADATA_REPLICATION_ED1" = X"" ]; then
-        echo "metadb_replication $METADATA_REPLICATION_ED" >> $GFMD_CONF
-    fi
-    if [ X"$METADATA_JOURNAL_DIR1" = X"" ]; then
-        echo "# mkdir following directory when metadb_replication is set to enable." >> $GFMD_CONF
-        echo "metadb_journal_dir $METADATA_JOURNAL_DIR" >> $GFMD_CONF
-    fi
+    tmp=`mktemp` || ABORT "cannot create a tmp file to update $GFMD_CONF"
+    egrep -v '(metadb_replication|metadb_journal_dir)' $GFMD_CONF > $tmp &&
+    echo "metadb_replication `tf2ed $METADATA_REPLICATION`" >> $tmp &&
+    echo "# mkdir following directory when metadb_replication is set to enable." >> $tmp &&
+    echo "metadb_journal_dir $METADATA_JOURNAL_DIR" >> $tmp &&
+    mv $tmp $GFMD_CONF || {
+	rm -f $tmp
+	ABORT "cannot update $GFMD_CONF"
+    }
 }
 
 update_first_set_param()
 {
-    : ${METADATA_REPLICATION_ED1=`getvalue metadb_replication`}
-    if [ X"$METADATA_REPLICATION_ED1" = X"enable" ]; then
-        METADATA_REPLICATION=true
-        METADATA_REPLICATION1=true
-        METADATA_REPLICATION_ED=enable
+    METADATA_REPLICATION_ED=`getvalue metadb_replication`
+    if [ X"$METADATA_REPLICATION_ED" = X"enable" ]; then
+        : ${METADATA_REPLICATION:=true}
     else
-        METADATA_REPLICATION1=false
+        : ${METADATA_REPLICATION:=false}
     fi
 
-    METADATA_JOURNAL_DIR1=`getvalue metadb_journal_dir`
-    : ${METADATA_JOURNAL_DIR:="$METADATA_JOURNAL_DIR1"}
-    : ${METADATA_JOURNAL_DIR:="$METADATA_JOURNAL_DIR0"}
+    : ${METADATA_JOURNAL_DIR:=`getvalue metadb_journal_dir`}
     : ${METADATA_JOURNAL_DIR:="$CONFIG_PREFIX/var/gfarm-metadata/journal"}
 }
 
@@ -163,8 +162,7 @@ update_first_set_param()
 #
 
 : ${BACKEND_OPTIONS:=}
-: ${METADATA_REPLICATION:=false}
-: ${METADATA_REPLICATION_ED:=disable}
+: ${BACKEND_TYPE:=}
 
 while [ $# -gt 0 ] ; do
 	case $1 in
@@ -183,7 +181,7 @@ while [ $# -gt 0 ] ; do
 		BACKEND_OPTIONS="$BACKEND_OPTIONS -f $1"
 		;;
 	  -j) shift; [ $# -ge 1 ] || usage
-		METADATA_JOURNAL_DIR0=$1
+		METADATA_JOURNAL_DIR=$1
 		;;
 
 	# control options
@@ -198,9 +196,8 @@ while [ $# -gt 0 ] ; do
 		;;
 	  -r)
 		METADATA_REPLICATION=true
-		METADATA_REPLICATION_ED=enable
 		;;
-	  --update|--update-symlink) 
+	  --update|--update-symlink)
 		UPDATE=true
 		;;
 
@@ -225,7 +222,7 @@ fi
 
 # sanity check
 if [ ! -f ${GFMD_CONF} ]; then
-	ABORT "${PROGNAME}: cannot find ${GFMD_CONF}, --prefix option required"
+	ABORT "cannot find ${GFMD_CONF}, --prefix option required"
 fi
 
 # determine a backend database type
@@ -271,6 +268,21 @@ update_sanity || ABORT "aborted"
 
 # -t option; display parameters
 $DISPLAY_PARAMS && display_params
+
+create_directory()
+{
+	# local d
+
+	for d
+	do
+		[ -d "$d" ] && continue
+		if mkdir -p "$d"; then
+			echo created "$d"
+		else
+			ABORT "mkdir -p $d, failed"
+		fi
+	done
+}
 
 update_postprocess_$BACKEND_TYPE || ABORT "aborted"
 
