- don't "restart" the service, but "start" it,   if pid file for the service doesn't exist. - add --help option
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/trunk@2965 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/config-gfarm/config-agent.in b/gftool/config-gfarm/config-agent.in
--- a/gftool/config-gfarm/config-agent.in
+++ b/gftool/config-gfarm/config-agent.in
@@ -49,7 +49,7 @@ fi
 
 usage()
 {
-	echo >&2 "usage: $PROGNAME [--prefix prefix] [-t] [-f]"
+	echo >&2 "usage: $PROGNAME [--help] [--prefix prefix] [-t] [-f]"
 	echo >&2 "	[-h hostname] [-p port]"
 	exit 1
 }
@@ -96,6 +96,9 @@ while [ $# -gt 0 ] ; do
 		;;
 
 	# control options
+	  --help)
+		usage
+		;;
 	  -N)
 		START_SERVICE=false
 		;;
@@ -109,7 +112,7 @@ while [ $# -gt 0 ] ; do
 		usage
 		;;
 	  *)
-		break
+		usage
 		;;
 	esac
 	shift
@@ -237,8 +240,9 @@ ABORT "$GFARM_CONF: cannot append agent related statements"
 mkscript $RC_DIR/gfarm_agent	config "$RC_AGENT_IN"
 
 if $START_SERVICE; then
-	service_add gfarm_agent && service_ctl gfarm_agent restart ||
-		ABORT "failed to start gfarm_agent"
+	if [ -f $RUN_DIR/gfarm_agent.pid ];then ctl=restart; else ctl=start; fi
+	service_add gfarm_agent && service_ctl gfarm_agent $ctl ||
+		ABORT "failed to $ctl gfarm_agent"
 fi
 echo "$PROGNAME success"
 exit 0
diff --git a/gftool/config-gfarm/config-gfarm.in b/gftool/config-gfarm/config-gfarm.in
--- a/gftool/config-gfarm/config-gfarm.in
+++ b/gftool/config-gfarm/config-gfarm.in
@@ -134,7 +134,7 @@ gen_passwd()
 
 usage()
 {
-	echo >&2 "usage: $PROGNAME [--prefix prefix] [-t] [-f] [-W] [-w]"
+	echo >&2 "usage: $PROGNAME [--help] [--prefix prefix] [-t] [-f] [-W] [-w]"
 	echo >&2 "	[-b metadata_backend] [-V metadata_backend_version]"
 	echo >&2 "	[-U backend_admin_user] [-u backend_user]"
 	echo >&2 "	[-d domain_name] [-h hostname]"
@@ -159,9 +159,14 @@ ABORT()
 # but some may not.
 start_service_common()
 {
+	if [ -f $RUN_DIR/$RC_BACKEND_BASENAME.pid ]; then
+		ctl=restart
+	else
+		ctl=start
+	fi
 	service_add $RC_BACKEND_BASENAME &&
-	service_ctl $RC_BACKEND_BASENAME restart ||
-		ABORT "failed to start $RC_BACKEND_BASENAME"
+	service_ctl $RC_BACKEND_BASENAME $ctl ${1+"$@"} ||
+		ABORT "failed to $ctl $RC_BACKEND_BASENAME"
 }
 
 sanity()
@@ -269,6 +274,9 @@ while [ $# -gt 0 ] ; do
 		;;
 
 	# control options
+	  --help)
+		usage
+		;;
 	  -N)
 		START_SERVICE=false
 		;;
@@ -540,9 +548,10 @@ apply_configuration_$BACKEND_TYPE
 if $START_SERVICE; then
 	start_service_$BACKEND_TYPE
 
+	if [ -f $RUN_DIR/gfmd.pid ]; then ctl=restart; else ctl=start; fi
 	service_add gfmd &&
-	service_ctl gfmd restart ||
-		ABORT "failed to start gfmd"
+	service_ctl gfmd $ctl ||
+		ABORT "failed to $ctl gfmd"
 fi
 
 echo "$PROGNAME success"
