This commit was manufactured by cvs2svn to create tag 'gfarm_v2_base'.
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/tags/gfarm_v2_base@2676 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/config-gfarm/config-gfarm.in b/gftool/config-gfarm/config-gfarm.in
--- a/gftool/config-gfarm/config-gfarm.in
+++ b/gftool/config-gfarm/config-gfarm.in
@@ -13,16 +13,16 @@ globus_location="@globus_location@"
 POSTGRESQL_TARGETS=postgresql
 LDAP_TARGETS=ldap
 backend_candidates="@postgresql_targets@ @ldap_targets@"
-case "@ldap_targets@" in
-'')	backend_default=postgresql;;
-*)	backend_default=ldap;;
+case "@postgresql_targets@" in
+'')	backend_default=ldap;;
+*)	backend_default=postgresql;;
 esac
 BACKEND_TYPE=$backend_default
 
 #
 PATH="${prefix}/bin:${prefix}/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/ucb:/usr/pkg/bin:/usr/pkg/sbin:/usr/local/bin:/usr/local/sbin:$PATH"
 export PATH
-search_path="$PATH":/usr/local/sbin:/usr/local/bin:/usr/pkg/sbin:/usr/pkg/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/ucb
+search_path="$PATH":/usr/local/sbin:/usr/local/bin:/usr/pkg/sbin:/usr/pkg/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/ucb:/usr/lib/postgresql/bin
 
 PROGNAME=`basename $0`
 
@@ -118,11 +118,11 @@ gen_passwd()
 usage()
 {
 	echo >&2 "usage: $PROGNAME [--prefix prefix] [-t] [-f] [-W] [-w]"
-	echo >&2 "	[-b metadata_backend]"
+	echo >&2 "	[-b metadata_backend] [-V metadata_backend_version]"
 	echo >&2 "	[-d domain_name] [-h hostname]"
-	echo >&2 "	[-V openldap_version] [-l metadata_directory]"
-	echo >&2 "	[-p postgresql/slapd_port] [-s gfsd_port] [-m gfmd_port]"
-	echo >&2 "  metadata_backend: 'ldap' or 'postgresql' (default is $backend_default)"
+	echo >&2 "	[-l metadata_directory] [-p metadata_backend_port]"
+	echo >&2 "	[-s gfsd_port] [-m gfmd_port]"
+	echo >&2 "  metadata_backend: $backend_candidates (default is $backend_default)"
 	exit 1
 }
 
@@ -138,11 +138,21 @@ sanity()
 	rv=0
 	case $BACKEND_TYPE in
 	postgresql)
-		if [ ! -x "$BACKEND_PREFIX/bin/pg_ctl" ]; then
+		case $BACKEND_VERSION in
+		[1-6].*|7.[0-3]|unknown)	# 7.3 or before
+			echo "WARNING: PostgreSQL version 7.4 or later required: $BACKEND_VERSION"
+			rv=1
+			;;
+		esac
+		if [ ! -x "$BACKEND_PREFIX/bin/pg_config" ]; then
+			echo "WARNING: command not found: pg_config" >&2
+			rv=1
+		fi
+		if [ ! -x "$PGSQL_BINDIR/pg_ctl" ]; then
 			echo "WARNING: command not found: pg_ctl" >&2
 			rv=1
 		fi
-		if [ ! -x "$BACKEND_PREFIX/bin/psql" ]; then
+		if [ ! -x "$PGSQL_BINDIR/psql" ]; then
 			echo "WARNING: command not found: psql" >&2
 			rv=1
 		fi
@@ -170,6 +180,7 @@ display_params()
 {
     echo     "prefix [--prefix]: $CONFIG_PREFIX"
     echo     "metadata backend    [-b]: $BACKEND_TYPE"
+    echo     "(supported backend: $backend_candidates)"
     case $BACKEND_TYPE in
     postgresql)
 	echo "postgresql admin user     [-U]: $BACKEND_ADMIN_USER"
@@ -177,6 +188,7 @@ display_params()
 	echo "postgresql user           [-u]: $BACKEND_USER"
 	echo "postgresql password       [-w]: `if [ -r $password ]; then cat $password; else echo '(auto generated)'; fi`"
 	echo "postgresql prefix   [-P]: $BACKEND_PREFIX"
+	echo "postgresql version  [-V]: $BACKEND_VERSION"
 	;;
     ldap)
 	echo "domain name         [-d]: $DOMAIN_NAME"
@@ -274,16 +286,18 @@ while [ $# -gt 0 ] ; do
 	  -W)
 		stty -echo;
 		( umask 077; 
-		  awk 'BEGIN{printf "admin password: ";}NR==1{print $0;exit}' \
-			> $admin_password
+		  printf "admin password: ";
+		  awk 'NR==1{print $0;exit}' > $admin_password
+		  echo
 		)
 		stty echo
 		;;
 	  -w)
 		stty -echo;
 		( umask 077;
-		  awk 'BEGIN{printf "user password: ";}NR==1{print $0;exit}' \
-			> $password
+		  printf "user password: ";
+		  awk 'NR==1{print $0;exit}' > $password
+		  echo
 		)
 		stty echo
 		;;
@@ -295,7 +309,7 @@ while [ $# -gt 0 ] ; do
 done
 
 #
-# search default $BACKEND_PREFIX for OpenLDAP
+# search default $BACKEND_PREFIX
 #
 
 case $BACKEND_TYPE in
@@ -307,8 +321,9 @@ postgresql)
 		IFS=$OIFS
 		for d
 		do
-			if [ -x "$d/pg_ctl" ]; then
+			if [ -x "$d/pg_config" ]; then
 				BACKEND_PREFIX=`dirname "$d"`
+				: ${PGSQL_BINDIR:=`$d/pg_config --bindir`}
 				break
 			fi
 		done
@@ -359,6 +374,7 @@ esac
 case $BACKEND_TYPE in
 postgresql)
 	: ${RC_BACKEND_BASENAME=gfarm-pgsql}
+	: ${PGSQL_BINDIR:="$BACKEND_PREFIX/bin"}
 	;;
 ldap)
 	: ${RC_BACKEND_BASENAME=gfarm-slapd}
@@ -400,7 +416,7 @@ fi
 
 : ${BACKEND_HOSTNAME:="$FQ_HOSTNAME"}
 [ X$BACKEND_HOSTNAME = X ] &&
-	ABORT 'cannot determine metadata server hostname'
+	ABORT 'cannot determine metadata server hostname, please specify it by -h option'
 
 case $BACKEND_TYPE in
 postgresql)
@@ -412,8 +428,27 @@ postgresql)
 	: ${DB_NAME:="gfarm"}
 	: ${BACKEND_ADMIN_USER:=${BACKEND_PRIVILEGE:-"`whoami`"}}
 	: ${BACKEND_USER:="gfarm"}
-	: ${BACKEND_PORT:="5432"}
+	# default PostgreSQL port number is 5432
+	: ${BACKEND_PORT:="602"}
 	: ${BACKEND_DATA_DIR:="$CONFIG_PREFIX/var/gfarm-pgsql"}
+
+	if [ -z "${BACKEND_VERSION-}" ]; then
+		if [ -x "$BACKEND_PREFIX/bin/pg_config" ]; then
+			BACKEND_VERSION=`$BACKEND_PREFIX/bin/pg_config --version 2>&1 |
+			  sed -n 's/.*PostgreSQL.* \([0-9][0-9]*\.[0-9][0-9]*\).*/\1/p'`
+			if [ -z "$BACKEND_VERSION" ]
+			then
+				BACKEND_VERSION="unknown"
+			elif expr "$BACKEND_VERSION" : '[0-9][0-9]*\.[0-9][0-9]*' \
+					>/dev/null; then
+				:
+			else
+				BACKEND_VERSION="unknown"
+			fi
+		else
+			BACKEND_VERSION="unknown"
+		fi
+	fi
 	;;
 
 ldap)
@@ -424,9 +459,10 @@ ldap)
 	: ${DOMAIN_NAME:=`dns_domainname`}
 	[ X"$DOMAIN_NAME" = X ] && ABORT 'cannot determine DNS domain name'
 
-	: ${BACKEND_PORT:="389"}
+	# official LDAP port number is 389
+	: ${BACKEND_PORT:="602"}
 
-	: ${LDAP_BASE_DN="dc=`echo ${DOMAIN_NAME} | sed -n -e 's/\./, dc=/gp'`"}
+	: ${LDAP_BASE_DN="dc=`echo ${DOMAIN_NAME} | sed -e 's/\./, dc=/g'`"}
 	: ${LDAP_LEAF_DC="`echo $LDAP_BASE_DN | sed -e 's/,.*//' -e 's/dc=//'`"}
 	: ${BACKEND_ADMIN_USER:="cn=root, $LDAP_BASE_DN"}
 	: ${BACKEND_USER:="$LDAP_BASE_DN"}
@@ -532,6 +568,7 @@ s|@config_gfarm_slapd_bdb_cachesize@|$SLAPD_BDB_CACHESIZE|g
 s|@config_gfarm_slapd_bdb_ncache@|$SLAPD_BDB_NCACHE|g
 s|@config_gfarm_openldap_libexec@|$OPENLDAP_LIBEXEC|g
 s|@config_gfarm_openldap_etc@|$OPENLDAP_ETC|g
+s|@config_gfarm_pgsql_bindir@|$PGSQL_BINDIR|g
 s|@config_gfarm_gfmd_port@|$GFMD_PORT|g
 s|@config_gfarm_gfmd_option@|-f $GFARM_CONF|g
 s|@config_gfarm_gfsd_port@|$GFSD_PORT|g
@@ -640,7 +677,7 @@ init_replace
 if [ -n "$BACKEND_PRIVILEGE" ]; then
 	chown "$BACKEND_PRIVILEGE" "$BACKEND_DATA_DIR" \
 		$admin_password $password
-	run_with_backend_privilege="su $BACKEND_PRIVILEGE /bin/sh"
+	run_with_backend_privilege="su - $BACKEND_PRIVILEGE -c /bin/sh"
 else
 	run_with_backend_privilege="/bin/sh"
 fi
@@ -654,16 +691,15 @@ mkcnf "$GFARM_CONF"	replace "$config_dir/gfarm.conf-$BACKEND_TYPE.in"
 
 case $BACKEND_TYPE in
 postgresql)
-	cat << _EOF_ | $run_with_backend_privilege
-	initdb -D '$BACKEND_DATA_DIR' --no-locale -E UTF-8 -A md5 \
-		--pwfile=$admin_password
+	cat << _EOF_ | $run_with_backend_privilege || ABORT "initdb failed"
+	$PGSQL_BINDIR/initdb -D "$BACKEND_DATA_DIR" --no-locale -E UTF-8
 _EOF_
 
 	# record the password
 	cp -p $admin_password $BACKEND_DATA_DIR/admin_password
 
-	mv "$BACKEND_DATA_DIR"/postgresql.conf \
-	   "$BACKEND_DATA_DIR"/postgresql.conf.org
+	cp -p "$BACKEND_DATA_DIR"/postgresql.conf \
+	      "$BACKEND_DATA_DIR"/postgresql.conf.org
 
 	awk '
 	/^[ 	]*#*[ 	]*listen_addresses[ 	]*=/ {
@@ -672,9 +708,21 @@ _EOF_
 		} else {
 			print $0
 		}
-		if (!listen_addresses_done) {
+		if (!tcpip_socket_done && !listen_addresses_done) {
 			print "listen_addresses = '"'*'"'"
 			listen_addresses_done = 1
+		}
+		next
+	}
+	/^[ 	]*#*[ 	]*tcpip_socket[ 	]*=/ {
+		if (/^[ 	]*tcpip_socket/) {
+			print "#" $0
+		} else {
+			print $0
+		}
+		if (!tcpip_socket_done && !listen_addresses_done) {
+			print "tcpip_socket = true"
+			tcpip_socket_done = 1
 		}
 		next
 	}
@@ -690,20 +738,76 @@ _EOF_
 		}
 		next
 	}
+	/^[ 	]*#*[ 	]*password_encryption[ 	]*=/ {
+		if (/^[ 	]*password_encryption/) {
+			print "#" $0
+		} else {
+			print $0
+		}
+		if (!password_encryption_done) {
+			print "password_encryption = true"
+			password_encryption_done = 1
+		}
+		next
+	}
+	/^[ 	]*#*[ 	]*autovacuum[ 	]*=/ {
+		if (/^[ 	]*autovacuum/) {
+			print "#" $0
+		} else {
+			print $0
+		}
+		if (!autovacuum_done) {
+			print "autovacuum = true"
+			autovacuum_done = 1
+		}
+		next
+	}
+	/^[ 	]*#*[ 	]*stats_row_level[ 	]*=/ {
+		if (/^[ 	]*stats_row_level/) {
+			print "#" $0
+		} else {
+			print $0
+		}
+		if (!stats_row_level_done) {
+			print "stats_row_level = on"
+			stats_row_level_done = 1
+		}
+		next
+	}
 	{print}
 	END {
-		if (!listen_addresses_done)
+		if (!listen_addresses_done && !tcpip_socket_done)
 			print "listen_addresses = '"'*'"'"
 		if (!port_done)
 			print "port = '$BACKEND_PORT'"
+		if (!password_encryption_done)
+			print "password_encryption = true"
+		# ignore autovacuum_done and stats_row_level_done for now.
+		# PostgreSQL should be earlier than 8.0.X
 	}'	 "$BACKEND_DATA_DIR"/postgresql.conf.org \
 		>"$BACKEND_DATA_DIR"/postgresql.conf
 
+	cp -p "$BACKEND_DATA_DIR"/pg_hba.conf \
+	      "$BACKEND_DATA_DIR"/pg_hba.conf.org
+
 	(
+	# all comment out
+	sed 's/^[0-9A-Za-z]/#&/' "$BACKEND_DATA_DIR"/pg_hba.conf.org
+
 	echo ""
-	echo "# TYPE	DATABASE	USER	IP-ADDRESS	NETMASK		METHOD"
-	echo "host	$DB_NAME		$BACKEND_USER	0.0.0.0		0.0.0.0		md5"
-	) >> "$BACKEND_DATA_DIR"/pg_hba.conf \
+	echo ""
+	echo "# TYPE	DATABASE	USER	CIDR-ADDRESS	METHOD"
+	echo ""
+	echo '# "local" is for Unix domain socket connections only'
+	echo 'local	all		all			md5'
+	echo '# IPv4 local connections:'
+	echo 'host	all		all	127.0.0.1/32	md5'
+	echo '# IPv6 local connections:'
+	echo '#host	all		all	::1/128		md5'
+
+	echo ""
+	echo "host	$DB_NAME		$BACKEND_USER	0.0.0.0/0	md5"
+	) > "$BACKEND_DATA_DIR"/pg_hba.conf
 	;;
 
 ldap)
@@ -733,10 +837,10 @@ mkscript "$RC_DIR/gfmd"			replace "$RC_GFMD_IN"
 case $BACKEND_TYPE in
 postgresql)
 	# backup configuration during temporary change
-	mv "$BACKEND_DATA_DIR"/postgresql.conf \
-	   "$BACKEND_DATA_DIR"/postgresql.conf.bak
-	mv "$BACKEND_DATA_DIR"/pg_hba.conf \
-	   "$BACKEND_DATA_DIR"/pg_hba.conf.bak
+	cp -p "$BACKEND_DATA_DIR"/postgresql.conf \
+	      "$BACKEND_DATA_DIR"/postgresql.conf.bak
+	cp -p "$BACKEND_DATA_DIR"/pg_hba.conf \
+	      "$BACKEND_DATA_DIR"/pg_hba.conf.bak
 
 	# create temporary configuration files 
 	awk '
@@ -746,10 +850,23 @@ postgresql)
 		} else {
 			print $0
 		}
-		if (!listen_addresses_done) {
+		if (!tcpip_socket_done && !listen_addresses_done) {
 			# disable TCP access to be sure
 			print "listen_addresses = '"''"'"
 			listen_addresses_done = 1
+		}
+		next
+	}
+	/^[ 	]*#*[ 	]*tcpip_socket[ 	]*=/ {
+		if (/^[ 	]*tcpip_socket/) {
+			print "#" $0
+		} else {
+			print $0
+		}
+		if (!tcpip_socket_done && !listen_addresses_done) {
+			# disable TCP access to be sure
+			print "tcpip_socket = false"
+			tcpip_socket_done = 1
 		}
 		next
 	}
@@ -768,7 +885,7 @@ postgresql)
 	}
 	{print}
 	END {
-		if (!listen_addresses_done)
+		if (!tcpip_socket_done && !listen_addresses_done)
 			print "listen_addresses = '"''"'"
 		if (!unix_socket_directory_done)
 			print "unix_socket_directory = '"'$BACKEND_DATA_DIR'"'"
@@ -781,30 +898,36 @@ postgresql)
 	# PostgreSQL-8.0.3.
 	# Also, we cannot use "restart" here, because it doesn't work either
 	# at first invocation.
-	$BACKEND_PREFIX/bin/pg_ctl -s -m fast \
+	cat << _EOF_ | $run_with_backend_privilege || ABORT "pg_ctl start failed"
+	$PGSQL_BINDIR/pg_ctl -s -m fast \
 		-D $BACKEND_DATA_DIR -l $BACKEND_DATA_DIR/logfile start
+_EOF_
 
 	# wait until portmaster actually starts. XXX are 3 seconds enough?
 	sleep 3
 
-	cat << _EOF_ | $run_with_backend_privilege
+	cat << _EOF_ | $run_with_backend_privilege || ABORT "createdb failed"
 	PGHOST="$BACKEND_DATA_DIR"; export PGHOST
 	PGPORT="$BACKEND_PORT"; export PGPORT
 	unset PGDATABASE PGUSER PGPASSWORD PGSERVICE
 	unset PGREALM PGOPTIONS PGSSLMODE PGREQUIRESSL PGCONNECT_TIMEOUT
 
-	createuser -A -D $BACKEND_USER
-	createdb $DB_NAME
-	psql -f "$config_dir/gfarm.sql" $DB_NAME
+	$PGSQL_BINDIR/createuser -A -D $BACKEND_USER
+	$PGSQL_BINDIR/createdb $DB_NAME
+	$PGSQL_BINDIR/psql -f "$config_dir/gfarm.sql" $DB_NAME
 	awk 'BEGIN {
 		print "GRANT SELECT, INSERT, UPDATE, DELETE"
 		print "	ON Host, HostAliases, Path, FileSection, FileSectionCopy"
 		print "	TO $BACKEND_USER;"
 	}
-	{
+	FILENAME == "$admin_password" {
+		print "ALTER USER $BACKEND_ADMIN_USER"
+		printf "  WITH ENCRYPTED PASSWORD '"'%s'"';\n", \$0
+	}
+	FILENAME == "$password" {
 		print "ALTER USER $BACKEND_USER"
 		printf "  WITH ENCRYPTED PASSWORD '"'%s'"';\n", \$0
-	}' $password | psql $DB_NAME
+	}' $admin_password $password | $PGSQL_BINDIR/psql $DB_NAME
 _EOF_
 
 	service_ctl $RC_BACKEND_BASENAME stop
