merge changes in gfarm v1.x branch to v2
git-svn-id: https://svn.code.sf.net/p/gfarm/code/gfarm/branches/gfarm_v2@3617 4a5e1ece-6a47-475c-b646-731d720b41d0

diff --git a/gftool/config-gfarm/config-gfsd.in b/gftool/config-gfarm/config-gfsd.in
--- a/gftool/config-gfarm/config-gfsd.in
+++ b/gftool/config-gfarm/config-gfsd.in
@@ -51,7 +51,7 @@ fi
 
 usage()
 {
-	echo >&2 "usage: $PROGNAME [--prefix prefix] [-t] [-f]"
+	echo >&2 "usage: $PROGNAME [--help] [--prefix prefix] [-t] [-f]"
 	echo >&2 "	[-a arch] [-p port] [-h hostname] [-n ncpu] spool_directory"
 	exit 1
 }
@@ -67,20 +67,27 @@ sanity()
 {
 	rv=0
 	if [ ! -x "$prefix/bin/gfhost" ]; then
-		echo "WARNING: command not found: $prefix/bin/gfhost" >&2
+		echo "ERROR: command not found: $prefix/bin/gfhost" >&2
 		rv=1
 	fi
+	case $SPOOL_DIRECTORY in
+	/*)	:;;
+	*)	echo "ERROR: spool directory ($SPOOL_DIRECTORY) must be absolute path"
+		rv=1;;
+	esac
 	return $rv
 }
 
 display_params()
 {
-	echo "prefix [--prefix]: $CONFIG_PREFIX"
-	echo "hostname     [-h]: $GFSD_HOSTNAME"
-	echo "architecture [-a]: $ARCH"
-	echo "port         [-p]: $GFSD_PORT"
-	echo "ncpu         [-n]: $NCPU"
-	echo "spool directory  : $SPOOL_DIRECTORY"
+	echo "prefix   [--prefix]: $CONFIG_PREFIX"
+	echo "hostname       [-h]: $GFSD_HOSTNAME"
+	echo "listen address [-l]: `if [ x$LISTEN_ADDRESS != x ]; then echo $LISTEN_ADDRESS; else echo '(all local IP addresses)'; fi`"
+	echo "architecture   [-a]: $ARCH"
+	echo "port           [-p]: $GFSD_PORT"
+	echo "ncpu           [-n]: $NCPU"
+	echo "spool directory    : $SPOOL_DIRECTORY"
+	echo "rc script name     : $RC_DIR/$RC_NAME"
 
 	sanity
 	exit 0
@@ -102,11 +109,17 @@ while [ $# -gt 0 ] ; do
 	  -h) shift; [ $# -ge 1 ] || usage
 		GFSD_HOSTNAME=$1
 		;;
+	  -l) shift; [ $# -ge 1 ] || usage
+		LISTEN_ADDRESS=$1
+		;;
 	  -n) shift; [ $# -ge 1 ] || usage
 		NCPU=$1
 		;;
 
 	# control options
+	  --help)
+		usage
+		;;
 	  -N)
 		START_SERVICE=false
 		;;
@@ -126,12 +139,10 @@ while [ $# -gt 0 ] ; do
 	shift
 done
 
-[ $# -eq 1 ] || usage
-
-SPOOL_DIRECTORY=$1
-case $SPOOL_DIRECTORY in
-	/*) break ;;
-	*) ABORT "$SPOOL_DIRECTORY: should be absolute path" ;;
+case $# in
+0)	:;; # see below
+1)	SPOOL_DIRECTORY=$1;;
+*)	usage;;
 esac
 
 . $prefix/share/gfarm/config/config-gfarm.sysdep
@@ -174,6 +185,22 @@ fi
 
 : ${RC_GFSD_IN="$config_dir/gfsd.in"}
 
+: ${LISTEN_ADDRESS:=""}
+
+if [ -n "$LISTEN_ADDRESS" ]; then
+	: ${SPOOL_DIRECTORY:="$CONFIG_PREFIX/var/gfarm-spool-$LISTEN_ADDRESS"}
+	: ${GFSD_EXTRA_OPTIONS:=" -l $LISTEN_ADDRESS"}
+	: ${RC_NAME:="gfsd-$LISTEN_ADDRESS"}
+	# $RC_VAR will be used as a shell variable name on *BSD ports & pkgsrc,
+	# thus, we only allow [0-9a-z_] as its value.
+	: ${RC_VAR:="`echo gfsd_$LISTEN_ADDRESS | sed 's/[^0-9a-z_]/_/g'`"}
+else
+	: ${SPOOL_DIRECTORY:="$CONFIG_PREFIX/var/gfarm-spool"}
+	: ${GFSD_EXTRA_OPTIONS:=""}
+	: ${RC_NAME:="gfsd"}
+	: ${RC_VAR:="$RC_NAME"}
+fi
+
 # -t option; display parameters
 $DISPLAY_PARAMS && display_params
 
@@ -184,11 +211,13 @@ sanity || ABORT "aborted"
 config()
 {
 	sed \
-	-e "s|@config_gfarm_prefix@|$prefix|" \
-	-e "s|@config_gfarm_globus_location@|${GLOBUS_LOCATION:-$globus_location}|" \
-	-e "s|@config_gfarm_gfarm_config@|$GFARM_CONF|" \
-	-e "s|@config_gfarm_gfsd_option@|-f $GFARM_CONF|" \
-	-e "s|@config_gfarm_run_dir@|$RUN_DIR|" \
+	-e "s|@config_gfarm_prefix@|$prefix|g" \
+	-e "s|@config_gfarm_globus_location@|${GLOBUS_LOCATION:-$globus_location}|g" \
+	-e "s|@config_gfarm_gfarm_config@|$GFARM_CONF|g" \
+	-e "s|@config_gfarm_gfsd_option@|-f $GFARM_CONF -r $SPOOL_DIRECTORY$GFSD_EXTRA_OPTIONS|g" \
+	-e "s|@config_gfarm_gfsd_rc_name@|$RC_NAME|g" \
+	-e "s|@config_gfarm_gfsd_rc_var@|$RC_VAR|g" \
+	-e "s|@config_gfarm_run_dir@|$RUN_DIR|g" \
 	${1+"$@"} | config_sysdep
 }
 
@@ -262,16 +291,8 @@ chown _gfarmfs $SPOOL_DIRECTORY ||
 
 mkcnf_gfsd_sysdep
 
-# create configuration files
-grep -v "^spool " $GFARM_CONF > $GFARM_CONF.tmp &&
-echo spool $SPOOL_DIRECTORY >> $GFARM_CONF.tmp &&
-echo spool_server_port $GFSD_PORT >> $GFARM_CONF.tmp &&
-mv $GFARM_CONF.tmp $GFARM_CONF &&
-echo $GFARM_CONF: updated ||
-ABORT "$GFARM_CONF: cannot append spool statement"
-
 # create run scripts
-mkscript $RC_DIR/gfsd	config "$RC_GFSD_IN"
+mkscript $RC_DIR/$RC_NAME	config "$RC_GFSD_IN"
 
 # gfhost
 if [ -z "${GLOBUS_LOCATION-}" ] && [ -n "$globus_location" ] &&
@@ -289,6 +310,9 @@ fi
 echo "$PROGNAME success"
 echo Please invoke the following command by admin_user:
 echo "$prefix/bin/gfhost" -c -a $ARCH -p $GFSD_PORT -n $NCPU $GFSD_HOSTNAME
+echo Then, please invoke the following command by root:
+# XXX FIXME should use "forcestart" instead of "start" on NetBSD and FreeBSD.
+echo "$RC_DIR/$RC_NAME start"
 exit 0
 
 # XXX not yet in gfarm v2
@@ -297,11 +321,13 @@ if $FORCE; then
 fi
 "$prefix/bin/gfhost" -c -a $ARCH -p $GFSD_PORT -n $NCPU $GFSD_HOSTNAME &&
 echo gfhost $GFSD_HOSTNAME: succeeded ||
-echo >&2 "gfhost $GFSD_HOSTNAME: failed"
+echo >&2 "gfhost -c -a $ARCH -n $NCPU $GFSD_HOSTNAME: failed"
 
 if $START_SERVICE; then
-	service_add gfsd && service_ctl gfsd restart ||
-		ABORT "failed to start gfsd"
+	if [ -f $RUN_DIR/$RC_NAME.pid ]; then ctl=restart; else ctl=start; fi
+	service_add $RC_NAME &&
+		service_ctl $RC_NAME $ctl ||
+		ABORT "failed to $ctl $RC_NAME"
 fi
 echo "$PROGNAME success"
 exit 0
